// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/minakeys/key_store.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type KeyStore struct {
	CosmosPublicKey string `protobuf:"bytes,1,opt,name=cosmosPublicKey,proto3" json:"cosmosPublicKey,omitempty"`
	MinaPublicKey   string `protobuf:"bytes,2,opt,name=minaPublicKey,proto3" json:"minaPublicKey,omitempty"`
	Creator         string `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *KeyStore) Reset()         { *m = KeyStore{} }
func (m *KeyStore) String() string { return proto.CompactTextString(m) }
func (*KeyStore) ProtoMessage()    {}
func (*KeyStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed7439721e59702, []int{0}
}
func (m *KeyStore) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyStore.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyStore.Merge(m, src)
}
func (m *KeyStore) XXX_Size() int {
	return m.Size()
}
func (m *KeyStore) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyStore.DiscardUnknown(m)
}

var xxx_messageInfo_KeyStore proto.InternalMessageInfo

func (m *KeyStore) GetCosmosPublicKey() string {
	if m != nil {
		return m.CosmosPublicKey
	}
	return ""
}

func (m *KeyStore) GetMinaPublicKey() string {
	if m != nil {
		return m.MinaPublicKey
	}
	return ""
}

func (m *KeyStore) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*KeyStore)(nil), "cosmos.minakeys.KeyStore")
}

func init() { proto.RegisterFile("cosmos/minakeys/key_store.proto", fileDescriptor_6ed7439721e59702) }

var fileDescriptor_6ed7439721e59702 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0xce, 0x2f, 0xce,
	0xcd, 0x2f, 0xd6, 0xcf, 0xcd, 0xcc, 0x4b, 0xcc, 0x4e, 0xad, 0x2c, 0xd6, 0xcf, 0x4e, 0xad, 0x8c,
	0x2f, 0x2e, 0xc9, 0x2f, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x87, 0x28, 0xd0,
	0x83, 0x29, 0x50, 0x2a, 0xe1, 0xe2, 0xf0, 0x4e, 0xad, 0x0c, 0x06, 0x29, 0x11, 0xd2, 0xe0, 0x82,
	0x4a, 0x07, 0x94, 0x26, 0xe5, 0x64, 0x26, 0x7b, 0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0xa1, 0x0b, 0x0b, 0xa9, 0x70, 0xf1, 0x82, 0x4c, 0x40, 0xa8, 0x63, 0x02, 0xab, 0x43, 0x15,
	0x14, 0x92, 0xe0, 0x62, 0x4f, 0x2e, 0x4a, 0x4d, 0x2c, 0xc9, 0x2f, 0x92, 0x60, 0x06, 0xcb, 0xc3,
	0xb8, 0x4e, 0x7e, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3,
	0x84, 0xc7, 0x72, 0x0c, 0x17, 0x1e, 0xcb, 0x31, 0xdc, 0x78, 0x2c, 0xc7, 0x10, 0x65, 0x92, 0x9e,
	0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x97, 0x9f, 0x92, 0x6a, 0x68, 0x60,
	0xa8, 0x9b, 0x99, 0xaf, 0x5f, 0x50, 0x9a, 0x53, 0x9c, 0x58, 0xa4, 0x0f, 0xf5, 0x5e, 0x05, 0xc2,
	0x83, 0x25, 0x95, 0x05, 0xa9, 0xc5, 0x49, 0x6c, 0x60, 0xdf, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x7b, 0x91, 0x25, 0x87, 0x00, 0x01, 0x00, 0x00,
}

func (m *KeyStore) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyStore) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyStore) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintKeyStore(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MinaPublicKey) > 0 {
		i -= len(m.MinaPublicKey)
		copy(dAtA[i:], m.MinaPublicKey)
		i = encodeVarintKeyStore(dAtA, i, uint64(len(m.MinaPublicKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CosmosPublicKey) > 0 {
		i -= len(m.CosmosPublicKey)
		copy(dAtA[i:], m.CosmosPublicKey)
		i = encodeVarintKeyStore(dAtA, i, uint64(len(m.CosmosPublicKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintKeyStore(dAtA []byte, offset int, v uint64) int {
	offset -= sovKeyStore(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *KeyStore) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CosmosPublicKey)
	if l > 0 {
		n += 1 + l + sovKeyStore(uint64(l))
	}
	l = len(m.MinaPublicKey)
	if l > 0 {
		n += 1 + l + sovKeyStore(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovKeyStore(uint64(l))
	}
	return n
}

func sovKeyStore(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozKeyStore(x uint64) (n int) {
	return sovKeyStore(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *KeyStore) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowKeyStore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeyStore: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeyStore: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeyStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeyStore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeyStore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosmosPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinaPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeyStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeyStore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeyStore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinaPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeyStore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeyStore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeyStore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipKeyStore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthKeyStore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipKeyStore(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowKeyStore
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKeyStore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKeyStore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthKeyStore
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupKeyStore
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthKeyStore
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthKeyStore        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowKeyStore          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupKeyStore = fmt.Errorf("proto: unexpected end of group")
)
