// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: interchain_security/minakeys/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75a691249d07bc5, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75a691249d07bc5, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetKeyStoreRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetKeyStoreRequest) Reset()         { *m = QueryGetKeyStoreRequest{} }
func (m *QueryGetKeyStoreRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetKeyStoreRequest) ProtoMessage()    {}
func (*QueryGetKeyStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75a691249d07bc5, []int{2}
}
func (m *QueryGetKeyStoreRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetKeyStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetKeyStoreRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetKeyStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetKeyStoreRequest.Merge(m, src)
}
func (m *QueryGetKeyStoreRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetKeyStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetKeyStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetKeyStoreRequest proto.InternalMessageInfo

func (m *QueryGetKeyStoreRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetKeyStoreResponse struct {
	KeyStore KeyStore `protobuf:"bytes,1,opt,name=keyStore,proto3" json:"keyStore"`
}

func (m *QueryGetKeyStoreResponse) Reset()         { *m = QueryGetKeyStoreResponse{} }
func (m *QueryGetKeyStoreResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetKeyStoreResponse) ProtoMessage()    {}
func (*QueryGetKeyStoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75a691249d07bc5, []int{3}
}
func (m *QueryGetKeyStoreResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetKeyStoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetKeyStoreResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetKeyStoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetKeyStoreResponse.Merge(m, src)
}
func (m *QueryGetKeyStoreResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetKeyStoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetKeyStoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetKeyStoreResponse proto.InternalMessageInfo

func (m *QueryGetKeyStoreResponse) GetKeyStore() KeyStore {
	if m != nil {
		return m.KeyStore
	}
	return KeyStore{}
}

type QueryAllKeyStoreRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllKeyStoreRequest) Reset()         { *m = QueryAllKeyStoreRequest{} }
func (m *QueryAllKeyStoreRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllKeyStoreRequest) ProtoMessage()    {}
func (*QueryAllKeyStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75a691249d07bc5, []int{4}
}
func (m *QueryAllKeyStoreRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllKeyStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllKeyStoreRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllKeyStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllKeyStoreRequest.Merge(m, src)
}
func (m *QueryAllKeyStoreRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllKeyStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllKeyStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllKeyStoreRequest proto.InternalMessageInfo

func (m *QueryAllKeyStoreRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllKeyStoreResponse struct {
	KeyStore   []KeyStore          `protobuf:"bytes,1,rep,name=keyStore,proto3" json:"keyStore"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllKeyStoreResponse) Reset()         { *m = QueryAllKeyStoreResponse{} }
func (m *QueryAllKeyStoreResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllKeyStoreResponse) ProtoMessage()    {}
func (*QueryAllKeyStoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75a691249d07bc5, []int{5}
}
func (m *QueryAllKeyStoreResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllKeyStoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllKeyStoreResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllKeyStoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllKeyStoreResponse.Merge(m, src)
}
func (m *QueryAllKeyStoreResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllKeyStoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllKeyStoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllKeyStoreResponse proto.InternalMessageInfo

func (m *QueryAllKeyStoreResponse) GetKeyStore() []KeyStore {
	if m != nil {
		return m.KeyStore
	}
	return nil
}

func (m *QueryAllKeyStoreResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetVoteExtRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetVoteExtRequest) Reset()         { *m = QueryGetVoteExtRequest{} }
func (m *QueryGetVoteExtRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetVoteExtRequest) ProtoMessage()    {}
func (*QueryGetVoteExtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75a691249d07bc5, []int{6}
}
func (m *QueryGetVoteExtRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVoteExtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVoteExtRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVoteExtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVoteExtRequest.Merge(m, src)
}
func (m *QueryGetVoteExtRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVoteExtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVoteExtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVoteExtRequest proto.InternalMessageInfo

func (m *QueryGetVoteExtRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetVoteExtResponse struct {
	VoteExt VoteExt `protobuf:"bytes,1,opt,name=voteExt,proto3" json:"voteExt"`
}

func (m *QueryGetVoteExtResponse) Reset()         { *m = QueryGetVoteExtResponse{} }
func (m *QueryGetVoteExtResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetVoteExtResponse) ProtoMessage()    {}
func (*QueryGetVoteExtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75a691249d07bc5, []int{7}
}
func (m *QueryGetVoteExtResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVoteExtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVoteExtResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVoteExtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVoteExtResponse.Merge(m, src)
}
func (m *QueryGetVoteExtResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVoteExtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVoteExtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVoteExtResponse proto.InternalMessageInfo

func (m *QueryGetVoteExtResponse) GetVoteExt() VoteExt {
	if m != nil {
		return m.VoteExt
	}
	return VoteExt{}
}

type QueryAllVoteExtRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllVoteExtRequest) Reset()         { *m = QueryAllVoteExtRequest{} }
func (m *QueryAllVoteExtRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllVoteExtRequest) ProtoMessage()    {}
func (*QueryAllVoteExtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75a691249d07bc5, []int{8}
}
func (m *QueryAllVoteExtRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllVoteExtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllVoteExtRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllVoteExtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllVoteExtRequest.Merge(m, src)
}
func (m *QueryAllVoteExtRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllVoteExtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllVoteExtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllVoteExtRequest proto.InternalMessageInfo

func (m *QueryAllVoteExtRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllVoteExtResponse struct {
	VoteExt    []VoteExt           `protobuf:"bytes,1,rep,name=voteExt,proto3" json:"voteExt"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllVoteExtResponse) Reset()         { *m = QueryAllVoteExtResponse{} }
func (m *QueryAllVoteExtResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllVoteExtResponse) ProtoMessage()    {}
func (*QueryAllVoteExtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75a691249d07bc5, []int{9}
}
func (m *QueryAllVoteExtResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllVoteExtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllVoteExtResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllVoteExtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllVoteExtResponse.Merge(m, src)
}
func (m *QueryAllVoteExtResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllVoteExtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllVoteExtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllVoteExtResponse proto.InternalMessageInfo

func (m *QueryAllVoteExtResponse) GetVoteExt() []VoteExt {
	if m != nil {
		return m.VoteExt
	}
	return nil
}

func (m *QueryAllVoteExtResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryVoteExtByHeightRequest struct {
	BlockHeight uint64             `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Pagination  *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryVoteExtByHeightRequest) Reset()         { *m = QueryVoteExtByHeightRequest{} }
func (m *QueryVoteExtByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVoteExtByHeightRequest) ProtoMessage()    {}
func (*QueryVoteExtByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75a691249d07bc5, []int{10}
}
func (m *QueryVoteExtByHeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVoteExtByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVoteExtByHeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVoteExtByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVoteExtByHeightRequest.Merge(m, src)
}
func (m *QueryVoteExtByHeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVoteExtByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVoteExtByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVoteExtByHeightRequest proto.InternalMessageInfo

func (m *QueryVoteExtByHeightRequest) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *QueryVoteExtByHeightRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryVoteExtByHeightResponse struct {
	VoteExt    []VoteExt           `protobuf:"bytes,1,rep,name=voteExt,proto3" json:"voteExt"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryVoteExtByHeightResponse) Reset()         { *m = QueryVoteExtByHeightResponse{} }
func (m *QueryVoteExtByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVoteExtByHeightResponse) ProtoMessage()    {}
func (*QueryVoteExtByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75a691249d07bc5, []int{11}
}
func (m *QueryVoteExtByHeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVoteExtByHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVoteExtByHeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVoteExtByHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVoteExtByHeightResponse.Merge(m, src)
}
func (m *QueryVoteExtByHeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVoteExtByHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVoteExtByHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVoteExtByHeightResponse proto.InternalMessageInfo

func (m *QueryVoteExtByHeightResponse) GetVoteExt() []VoteExt {
	if m != nil {
		return m.VoteExt
	}
	return nil
}

func (m *QueryVoteExtByHeightResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetMinaPubkeyRequest struct {
	ValidatorAddr string `protobuf:"bytes,1,opt,name=validatorAddr,proto3" json:"validatorAddr,omitempty"`
}

func (m *QueryGetMinaPubkeyRequest) Reset()         { *m = QueryGetMinaPubkeyRequest{} }
func (m *QueryGetMinaPubkeyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMinaPubkeyRequest) ProtoMessage()    {}
func (*QueryGetMinaPubkeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75a691249d07bc5, []int{12}
}
func (m *QueryGetMinaPubkeyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMinaPubkeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMinaPubkeyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMinaPubkeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMinaPubkeyRequest.Merge(m, src)
}
func (m *QueryGetMinaPubkeyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMinaPubkeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMinaPubkeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMinaPubkeyRequest proto.InternalMessageInfo

func (m *QueryGetMinaPubkeyRequest) GetValidatorAddr() string {
	if m != nil {
		return m.ValidatorAddr
	}
	return ""
}

type QueryGetMinaPubkeyResponse struct {
	X     string `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	IsOdd string `protobuf:"bytes,2,opt,name=is_odd,json=isOdd,proto3" json:"is_odd,omitempty"`
}

func (m *QueryGetMinaPubkeyResponse) Reset()         { *m = QueryGetMinaPubkeyResponse{} }
func (m *QueryGetMinaPubkeyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMinaPubkeyResponse) ProtoMessage()    {}
func (*QueryGetMinaPubkeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75a691249d07bc5, []int{13}
}
func (m *QueryGetMinaPubkeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMinaPubkeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMinaPubkeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMinaPubkeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMinaPubkeyResponse.Merge(m, src)
}
func (m *QueryGetMinaPubkeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMinaPubkeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMinaPubkeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMinaPubkeyResponse proto.InternalMessageInfo

func (m *QueryGetMinaPubkeyResponse) GetX() string {
	if m != nil {
		return m.X
	}
	return ""
}

func (m *QueryGetMinaPubkeyResponse) GetIsOdd() string {
	if m != nil {
		return m.IsOdd
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "interchain_security.minakeys.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "interchain_security.minakeys.QueryParamsResponse")
	proto.RegisterType((*QueryGetKeyStoreRequest)(nil), "interchain_security.minakeys.QueryGetKeyStoreRequest")
	proto.RegisterType((*QueryGetKeyStoreResponse)(nil), "interchain_security.minakeys.QueryGetKeyStoreResponse")
	proto.RegisterType((*QueryAllKeyStoreRequest)(nil), "interchain_security.minakeys.QueryAllKeyStoreRequest")
	proto.RegisterType((*QueryAllKeyStoreResponse)(nil), "interchain_security.minakeys.QueryAllKeyStoreResponse")
	proto.RegisterType((*QueryGetVoteExtRequest)(nil), "interchain_security.minakeys.QueryGetVoteExtRequest")
	proto.RegisterType((*QueryGetVoteExtResponse)(nil), "interchain_security.minakeys.QueryGetVoteExtResponse")
	proto.RegisterType((*QueryAllVoteExtRequest)(nil), "interchain_security.minakeys.QueryAllVoteExtRequest")
	proto.RegisterType((*QueryAllVoteExtResponse)(nil), "interchain_security.minakeys.QueryAllVoteExtResponse")
	proto.RegisterType((*QueryVoteExtByHeightRequest)(nil), "interchain_security.minakeys.QueryVoteExtByHeightRequest")
	proto.RegisterType((*QueryVoteExtByHeightResponse)(nil), "interchain_security.minakeys.QueryVoteExtByHeightResponse")
	proto.RegisterType((*QueryGetMinaPubkeyRequest)(nil), "interchain_security.minakeys.QueryGetMinaPubkeyRequest")
	proto.RegisterType((*QueryGetMinaPubkeyResponse)(nil), "interchain_security.minakeys.QueryGetMinaPubkeyResponse")
}

func init() {
	proto.RegisterFile("interchain_security/minakeys/query.proto", fileDescriptor_e75a691249d07bc5)
}

var fileDescriptor_e75a691249d07bc5 = []byte{
	// 864 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x96, 0xcd, 0x6b, 0x33, 0x45,
	0x1c, 0xc7, 0x33, 0x7d, 0x49, 0xdb, 0x69, 0x8b, 0x38, 0x56, 0xad, 0x6b, 0x89, 0xba, 0xd4, 0xbe,
	0x59, 0x77, 0x9a, 0xbe, 0x5a, 0x15, 0x21, 0xc5, 0xda, 0x82, 0x14, 0x6b, 0x04, 0x0f, 0x1e, 0x4c,
	0x27, 0xd9, 0x61, 0xb3, 0x64, 0xb3, 0xb3, 0xdd, 0x9d, 0x84, 0x2c, 0xa5, 0x20, 0x9e, 0x3c, 0x0a,
	0x1e, 0xfd, 0x07, 0xec, 0xa1, 0x45, 0xfc, 0x1f, 0x84, 0x9e, 0xa4, 0xe0, 0xc5, 0x93, 0x48, 0x2b,
	0x3c, 0xff, 0xc6, 0xc3, 0xce, 0xce, 0x26, 0xdd, 0x24, 0xec, 0xb3, 0x09, 0x3d, 0x3c, 0x97, 0xb2,
	0x9d, 0xfc, 0x5e, 0x3e, 0xbf, 0xef, 0x6f, 0xf2, 0xcd, 0xc2, 0x15, 0xd3, 0xe6, 0xd4, 0xad, 0x54,
	0x89, 0x69, 0x97, 0x3c, 0x5a, 0x69, 0xb8, 0x26, 0xf7, 0x71, 0xdd, 0xb4, 0x49, 0x8d, 0xfa, 0x1e,
	0x3e, 0x6f, 0x50, 0xd7, 0xd7, 0x1c, 0x97, 0x71, 0x86, 0x16, 0xfa, 0x44, 0x6a, 0x51, 0xa4, 0xf2,
	0x2a, 0xa9, 0x9b, 0x36, 0xc3, 0xe2, 0x6f, 0x98, 0xa0, 0xcc, 0x19, 0xcc, 0x60, 0xe2, 0x11, 0x07,
	0x4f, 0xf2, 0x74, 0xc1, 0x60, 0xcc, 0xb0, 0x28, 0x26, 0x8e, 0x89, 0x89, 0x6d, 0x33, 0x4e, 0xb8,
	0xc9, 0x6c, 0x4f, 0x7e, 0xba, 0x56, 0x61, 0x5e, 0x9d, 0x79, 0xb8, 0x4c, 0x3c, 0x1a, 0x76, 0xc7,
	0xcd, 0x7c, 0x99, 0x72, 0x92, 0xc7, 0x0e, 0x31, 0x4c, 0x5b, 0x04, 0xcb, 0xd8, 0xd5, 0x44, 0x74,
	0x87, 0xb8, 0xa4, 0x1e, 0x95, 0x5d, 0x4f, 0x0c, 0xad, 0x51, 0xbf, 0xe4, 0x71, 0xe6, 0x52, 0x19,
	0xfd, 0x41, 0x62, 0x74, 0x93, 0x71, 0x5a, 0xa2, 0x2d, 0x1e, 0x06, 0xab, 0x73, 0x10, 0x7d, 0x1d,
	0x70, 0x9e, 0x8a, 0x7e, 0x45, 0x7a, 0xde, 0xa0, 0x1e, 0x57, 0xbf, 0x87, 0xaf, 0xc5, 0x4e, 0x3d,
	0x87, 0xd9, 0x1e, 0x45, 0x47, 0x30, 0x1b, 0x72, 0xcd, 0x83, 0x77, 0xc1, 0xca, 0xf4, 0xe6, 0xa2,
	0x96, 0x24, 0xaa, 0x16, 0x66, 0x1f, 0x4c, 0xdd, 0xfe, 0xfb, 0x4e, 0xe6, 0xb7, 0x67, 0xbf, 0xaf,
	0x81, 0xa2, 0x4c, 0x57, 0x31, 0x7c, 0x53, 0xd4, 0x3f, 0xa2, 0xfc, 0x4b, 0xea, 0x7f, 0x13, 0xc0,
	0xcb, 0xd6, 0x68, 0x0e, 0x8e, 0x9b, 0xb6, 0x4e, 0x5b, 0xa2, 0xc5, 0x54, 0x31, 0xfc, 0x47, 0xd5,
	0xe1, 0x7c, 0x6f, 0x82, 0xa4, 0x3a, 0x86, 0x93, 0x35, 0x79, 0x26, 0xb9, 0x96, 0x92, 0xb9, 0xa2,
	0x0a, 0x07, 0x63, 0x01, 0x59, 0xb1, 0x9d, 0xad, 0x12, 0x89, 0x55, 0xb0, 0xac, 0x6e, 0xac, 0x2f,
	0x20, 0xec, 0x6c, 0xb0, 0xdd, 0x26, 0x5c, 0xb7, 0x16, 0xac, 0x5b, 0x0b, 0x2f, 0x9b, 0x5c, 0xb7,
	0x76, 0x4a, 0x8c, 0x28, 0xb7, 0xf8, 0x28, 0x53, 0xbd, 0x06, 0x72, 0x92, 0x58, 0x8f, 0xbe, 0x93,
	0x8c, 0x0e, 0x3f, 0x09, 0x3a, 0x8a, 0xe1, 0x8e, 0x08, 0xdc, 0xe5, 0x17, 0xe2, 0x86, 0x18, 0x31,
	0x5e, 0x0d, 0xbe, 0x11, 0x09, 0xff, 0x2d, 0xe3, 0xf4, 0xb0, 0xc5, 0x93, 0x17, 0x75, 0xd6, 0xd9,
	0x6c, 0x3b, 0x5e, 0x4e, 0x77, 0x08, 0x27, 0x9a, 0xe1, 0x91, 0xd4, 0xef, 0xfd, 0xe4, 0xe1, 0x64,
	0xbe, 0x9c, 0x2d, 0xca, 0x55, 0xcf, 0x24, 0x51, 0xc1, 0xb2, 0xba, 0x88, 0x9e, 0x6a, 0x47, 0x57,
	0xa0, 0x73, 0x0f, 0x12, 0x87, 0x18, 0x1d, 0x76, 0x88, 0xa7, 0xdb, 0xcf, 0x4f, 0x00, 0xbe, 0x2d,
	0x58, 0xa3, 0x46, 0xfe, 0x31, 0x35, 0x8d, 0x6a, 0x5b, 0x93, 0xf7, 0xe0, 0x4c, 0xd9, 0x62, 0x95,
	0x5a, 0xa9, 0x2a, 0x8e, 0x85, 0x2a, 0x63, 0xc5, 0x69, 0x71, 0x16, 0x46, 0x76, 0xc9, 0x36, 0x32,
	0xb4, 0x6c, 0x37, 0x00, 0x2e, 0xf4, 0x47, 0x79, 0x49, 0xb5, 0x2b, 0xc0, 0xb7, 0xa2, 0xbb, 0x7a,
	0x62, 0xda, 0xe4, 0xb4, 0x51, 0xae, 0x51, 0x3f, 0x12, 0x6e, 0x11, 0xce, 0x36, 0x89, 0x65, 0xea,
	0x84, 0x33, 0xb7, 0xa0, 0xeb, 0xae, 0xbc, 0xe6, 0xf1, 0x43, 0xb5, 0x00, 0x95, 0x7e, 0x25, 0xe4,
	0xc0, 0x33, 0x10, 0x44, 0x5f, 0x0f, 0xd0, 0x42, 0xaf, 0xc3, 0xac, 0xe9, 0x95, 0x98, 0xae, 0x0b,
	0xe6, 0xe0, 0x1b, 0xe3, 0x7d, 0xa5, 0xeb, 0x9b, 0x3f, 0x40, 0x38, 0x2e, 0x6a, 0xa0, 0x5f, 0x01,
	0xcc, 0x86, 0x9e, 0x89, 0x36, 0x92, 0x95, 0xe9, 0xb5, 0x6c, 0x25, 0x3f, 0x40, 0x46, 0x88, 0xa7,
	0xae, 0xff, 0xf8, 0xf7, 0xff, 0xbf, 0x8c, 0x2c, 0xa1, 0x45, 0x9c, 0xe2, 0xa7, 0x08, 0xfd, 0x01,
	0xe0, 0x64, 0xe4, 0x37, 0x68, 0x27, 0x45, 0xb7, 0x5e, 0x73, 0x57, 0x76, 0x07, 0x4d, 0x93, 0xa4,
	0x7b, 0x82, 0x34, 0x8f, 0x30, 0x4e, 0xf7, 0x4b, 0x88, 0x2f, 0x84, 0x1b, 0x5d, 0xa2, 0x6b, 0x00,
	0xa7, 0xa3, 0x6a, 0x05, 0xcb, 0x4a, 0xc5, 0xdd, 0xeb, 0xfe, 0xa9, 0xb8, 0xfb, 0x18, 0xba, 0x8a,
	0x05, 0xf7, 0x2a, 0x5a, 0x4e, 0xc9, 0x8d, 0x6e, 0x00, 0x9c, 0x90, 0xd7, 0x1e, 0x6d, 0xa7, 0x13,
	0x2b, 0x6e, 0x82, 0xca, 0xce, 0x80, 0x59, 0x92, 0x74, 0x57, 0x90, 0x6e, 0x20, 0x0d, 0xa7, 0x7a,
	0x7b, 0x68, 0x0b, 0x7c, 0x05, 0x20, 0x94, 0xb5, 0x02, 0x7d, 0xb7, 0xd3, 0x09, 0x35, 0x04, 0x73,
	0xaf, 0x17, 0xab, 0x9a, 0x60, 0x5e, 0x41, 0x4b, 0xe9, 0x98, 0xd1, 0x5f, 0x00, 0xbe, 0xd2, 0xe5,
	0x4d, 0x68, 0x3f, 0x45, 0xeb, 0xfe, 0xd6, 0xaa, 0x7c, 0x3c, 0x4c, 0xaa, 0x44, 0xff, 0x5c, 0xa0,
	0x7f, 0x86, 0x3e, 0x4d, 0x29, 0x77, 0xe8, 0xde, 0xf8, 0xe2, 0xb1, 0x97, 0x5f, 0xa2, 0x3f, 0x01,
	0x9c, 0x8d, 0x39, 0x0f, 0xda, 0x4b, 0xb7, 0xfd, 0x1e, 0xbb, 0x53, 0x3e, 0x1a, 0x3c, 0x51, 0x8e,
	0x52, 0x10, 0xa3, 0x7c, 0x82, 0xf6, 0x93, 0x47, 0x09, 0x1e, 0x4a, 0x8e, 0x48, 0xc5, 0x17, 0x31,
	0x13, 0xbd, 0x3c, 0x38, 0xb9, 0xbd, 0xcf, 0x81, 0xbb, 0xfb, 0x1c, 0xf8, 0xef, 0x3e, 0x07, 0x7e,
	0x7e, 0xc8, 0x65, 0xee, 0x1e, 0x72, 0x99, 0x7f, 0x1e, 0x72, 0x99, 0xef, 0xb6, 0x0c, 0x93, 0x57,
	0x1b, 0x65, 0xad, 0xc2, 0xea, 0xd8, 0x66, 0x3a, 0xcd, 0x6f, 0xe4, 0x3f, 0x34, 0x19, 0x76, 0x1a,
	0x96, 0x47, 0x5c, 0x2c, 0x7a, 0xe1, 0x56, 0xa7, 0x09, 0xf7, 0x1d, 0xea, 0x95, 0xb3, 0xe2, 0xd5,
	0x76, 0xeb, 0x79, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0x38, 0x08, 0x0f, 0x1d, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of KeyStore items.
	KeyStore(ctx context.Context, in *QueryGetKeyStoreRequest, opts ...grpc.CallOption) (*QueryGetKeyStoreResponse, error)
	KeyStoreAll(ctx context.Context, in *QueryAllKeyStoreRequest, opts ...grpc.CallOption) (*QueryAllKeyStoreResponse, error)
	// Queries a list of VoteExt items.
	VoteExt(ctx context.Context, in *QueryGetVoteExtRequest, opts ...grpc.CallOption) (*QueryGetVoteExtResponse, error)
	VoteExtAll(ctx context.Context, in *QueryAllVoteExtRequest, opts ...grpc.CallOption) (*QueryAllVoteExtResponse, error)
	// Queries VoteExt items by height.
	VoteExtByHeight(ctx context.Context, in *QueryVoteExtByHeightRequest, opts ...grpc.CallOption) (*QueryVoteExtByHeightResponse, error)
	GetMinaPubkey(ctx context.Context, in *QueryGetMinaPubkeyRequest, opts ...grpc.CallOption) (*QueryGetMinaPubkeyResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/interchain_security.minakeys.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) KeyStore(ctx context.Context, in *QueryGetKeyStoreRequest, opts ...grpc.CallOption) (*QueryGetKeyStoreResponse, error) {
	out := new(QueryGetKeyStoreResponse)
	err := c.cc.Invoke(ctx, "/interchain_security.minakeys.Query/KeyStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) KeyStoreAll(ctx context.Context, in *QueryAllKeyStoreRequest, opts ...grpc.CallOption) (*QueryAllKeyStoreResponse, error) {
	out := new(QueryAllKeyStoreResponse)
	err := c.cc.Invoke(ctx, "/interchain_security.minakeys.Query/KeyStoreAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VoteExt(ctx context.Context, in *QueryGetVoteExtRequest, opts ...grpc.CallOption) (*QueryGetVoteExtResponse, error) {
	out := new(QueryGetVoteExtResponse)
	err := c.cc.Invoke(ctx, "/interchain_security.minakeys.Query/VoteExt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VoteExtAll(ctx context.Context, in *QueryAllVoteExtRequest, opts ...grpc.CallOption) (*QueryAllVoteExtResponse, error) {
	out := new(QueryAllVoteExtResponse)
	err := c.cc.Invoke(ctx, "/interchain_security.minakeys.Query/VoteExtAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VoteExtByHeight(ctx context.Context, in *QueryVoteExtByHeightRequest, opts ...grpc.CallOption) (*QueryVoteExtByHeightResponse, error) {
	out := new(QueryVoteExtByHeightResponse)
	err := c.cc.Invoke(ctx, "/interchain_security.minakeys.Query/VoteExtByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetMinaPubkey(ctx context.Context, in *QueryGetMinaPubkeyRequest, opts ...grpc.CallOption) (*QueryGetMinaPubkeyResponse, error) {
	out := new(QueryGetMinaPubkeyResponse)
	err := c.cc.Invoke(ctx, "/interchain_security.minakeys.Query/GetMinaPubkey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of KeyStore items.
	KeyStore(context.Context, *QueryGetKeyStoreRequest) (*QueryGetKeyStoreResponse, error)
	KeyStoreAll(context.Context, *QueryAllKeyStoreRequest) (*QueryAllKeyStoreResponse, error)
	// Queries a list of VoteExt items.
	VoteExt(context.Context, *QueryGetVoteExtRequest) (*QueryGetVoteExtResponse, error)
	VoteExtAll(context.Context, *QueryAllVoteExtRequest) (*QueryAllVoteExtResponse, error)
	// Queries VoteExt items by height.
	VoteExtByHeight(context.Context, *QueryVoteExtByHeightRequest) (*QueryVoteExtByHeightResponse, error)
	GetMinaPubkey(context.Context, *QueryGetMinaPubkeyRequest) (*QueryGetMinaPubkeyResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) KeyStore(ctx context.Context, req *QueryGetKeyStoreRequest) (*QueryGetKeyStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeyStore not implemented")
}
func (*UnimplementedQueryServer) KeyStoreAll(ctx context.Context, req *QueryAllKeyStoreRequest) (*QueryAllKeyStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeyStoreAll not implemented")
}
func (*UnimplementedQueryServer) VoteExt(ctx context.Context, req *QueryGetVoteExtRequest) (*QueryGetVoteExtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteExt not implemented")
}
func (*UnimplementedQueryServer) VoteExtAll(ctx context.Context, req *QueryAllVoteExtRequest) (*QueryAllVoteExtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteExtAll not implemented")
}
func (*UnimplementedQueryServer) VoteExtByHeight(ctx context.Context, req *QueryVoteExtByHeightRequest) (*QueryVoteExtByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteExtByHeight not implemented")
}
func (*UnimplementedQueryServer) GetMinaPubkey(ctx context.Context, req *QueryGetMinaPubkeyRequest) (*QueryGetMinaPubkeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMinaPubkey not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.minakeys.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_KeyStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetKeyStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).KeyStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.minakeys.Query/KeyStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).KeyStore(ctx, req.(*QueryGetKeyStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_KeyStoreAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllKeyStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).KeyStoreAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.minakeys.Query/KeyStoreAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).KeyStoreAll(ctx, req.(*QueryAllKeyStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VoteExt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetVoteExtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VoteExt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.minakeys.Query/VoteExt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VoteExt(ctx, req.(*QueryGetVoteExtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VoteExtAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllVoteExtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VoteExtAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.minakeys.Query/VoteExtAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VoteExtAll(ctx, req.(*QueryAllVoteExtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VoteExtByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVoteExtByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VoteExtByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.minakeys.Query/VoteExtByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VoteExtByHeight(ctx, req.(*QueryVoteExtByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetMinaPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMinaPubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetMinaPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.minakeys.Query/GetMinaPubkey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetMinaPubkey(ctx, req.(*QueryGetMinaPubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "interchain_security.minakeys.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "KeyStore",
			Handler:    _Query_KeyStore_Handler,
		},
		{
			MethodName: "KeyStoreAll",
			Handler:    _Query_KeyStoreAll_Handler,
		},
		{
			MethodName: "VoteExt",
			Handler:    _Query_VoteExt_Handler,
		},
		{
			MethodName: "VoteExtAll",
			Handler:    _Query_VoteExtAll_Handler,
		},
		{
			MethodName: "VoteExtByHeight",
			Handler:    _Query_VoteExtByHeight_Handler,
		},
		{
			MethodName: "GetMinaPubkey",
			Handler:    _Query_GetMinaPubkey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interchain_security/minakeys/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetKeyStoreRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetKeyStoreRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetKeyStoreRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetKeyStoreResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetKeyStoreResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetKeyStoreResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.KeyStore.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllKeyStoreRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllKeyStoreRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllKeyStoreRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllKeyStoreResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllKeyStoreResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllKeyStoreResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.KeyStore) > 0 {
		for iNdEx := len(m.KeyStore) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.KeyStore[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVoteExtRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVoteExtRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVoteExtRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVoteExtResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVoteExtResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVoteExtResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.VoteExt.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllVoteExtRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllVoteExtRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllVoteExtRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllVoteExtResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllVoteExtResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllVoteExtResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.VoteExt) > 0 {
		for iNdEx := len(m.VoteExt) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VoteExt[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryVoteExtByHeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVoteExtByHeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVoteExtByHeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.BlockHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryVoteExtByHeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVoteExtByHeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVoteExtByHeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.VoteExt) > 0 {
		for iNdEx := len(m.VoteExt) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VoteExt[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMinaPubkeyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMinaPubkeyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMinaPubkeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorAddr) > 0 {
		i -= len(m.ValidatorAddr)
		copy(dAtA[i:], m.ValidatorAddr)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValidatorAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMinaPubkeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMinaPubkeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMinaPubkeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IsOdd) > 0 {
		i -= len(m.IsOdd)
		copy(dAtA[i:], m.IsOdd)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.IsOdd)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.X) > 0 {
		i -= len(m.X)
		copy(dAtA[i:], m.X)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.X)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetKeyStoreRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetKeyStoreResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.KeyStore.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllKeyStoreRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllKeyStoreResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.KeyStore) > 0 {
		for _, e := range m.KeyStore {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetVoteExtRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetVoteExtResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.VoteExt.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllVoteExtRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllVoteExtResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.VoteExt) > 0 {
		for _, e := range m.VoteExt {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVoteExtByHeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovQuery(uint64(m.BlockHeight))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVoteExtByHeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.VoteExt) > 0 {
		for _, e := range m.VoteExt {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetMinaPubkeyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddr)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetMinaPubkeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.X)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.IsOdd)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetKeyStoreRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetKeyStoreRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetKeyStoreRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetKeyStoreResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetKeyStoreResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetKeyStoreResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyStore", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.KeyStore.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllKeyStoreRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllKeyStoreRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllKeyStoreRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllKeyStoreResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllKeyStoreResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllKeyStoreResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyStore", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyStore = append(m.KeyStore, KeyStore{})
			if err := m.KeyStore[len(m.KeyStore)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVoteExtRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVoteExtRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVoteExtRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVoteExtResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVoteExtResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVoteExtResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteExt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VoteExt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllVoteExtRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllVoteExtRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllVoteExtRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllVoteExtResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllVoteExtResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllVoteExtResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteExt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VoteExt = append(m.VoteExt, VoteExt{})
			if err := m.VoteExt[len(m.VoteExt)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVoteExtByHeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVoteExtByHeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVoteExtByHeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVoteExtByHeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVoteExtByHeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVoteExtByHeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteExt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VoteExt = append(m.VoteExt, VoteExt{})
			if err := m.VoteExt[len(m.VoteExt)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMinaPubkeyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMinaPubkeyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMinaPubkeyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMinaPubkeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMinaPubkeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMinaPubkeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.X = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsOdd", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IsOdd = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
