// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: interchain_security/minakeys/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e22f197626938e4, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e22f197626938e4, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgCreateKeyStore struct {
	Creator         string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	CosmosPublicKey string `protobuf:"bytes,2,opt,name=cosmosPublicKey,proto3" json:"cosmosPublicKey,omitempty"`
	MinaPublicKey   string `protobuf:"bytes,3,opt,name=minaPublicKey,proto3" json:"minaPublicKey,omitempty"`
	CosmosSignature []byte `protobuf:"bytes,4,opt,name=cosmosSignature,proto3" json:"cosmosSignature,omitempty"`
	MinaSignature   []byte `protobuf:"bytes,5,opt,name=minaSignature,proto3" json:"minaSignature,omitempty"`
}

func (m *MsgCreateKeyStore) Reset()         { *m = MsgCreateKeyStore{} }
func (m *MsgCreateKeyStore) String() string { return proto.CompactTextString(m) }
func (*MsgCreateKeyStore) ProtoMessage()    {}
func (*MsgCreateKeyStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e22f197626938e4, []int{2}
}
func (m *MsgCreateKeyStore) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateKeyStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateKeyStore.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateKeyStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateKeyStore.Merge(m, src)
}
func (m *MsgCreateKeyStore) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateKeyStore) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateKeyStore.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateKeyStore proto.InternalMessageInfo

func (m *MsgCreateKeyStore) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateKeyStore) GetCosmosPublicKey() string {
	if m != nil {
		return m.CosmosPublicKey
	}
	return ""
}

func (m *MsgCreateKeyStore) GetMinaPublicKey() string {
	if m != nil {
		return m.MinaPublicKey
	}
	return ""
}

func (m *MsgCreateKeyStore) GetCosmosSignature() []byte {
	if m != nil {
		return m.CosmosSignature
	}
	return nil
}

func (m *MsgCreateKeyStore) GetMinaSignature() []byte {
	if m != nil {
		return m.MinaSignature
	}
	return nil
}

type MsgCreateKeyStoreResponse struct {
}

func (m *MsgCreateKeyStoreResponse) Reset()         { *m = MsgCreateKeyStoreResponse{} }
func (m *MsgCreateKeyStoreResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateKeyStoreResponse) ProtoMessage()    {}
func (*MsgCreateKeyStoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e22f197626938e4, []int{3}
}
func (m *MsgCreateKeyStoreResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateKeyStoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateKeyStoreResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateKeyStoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateKeyStoreResponse.Merge(m, src)
}
func (m *MsgCreateKeyStoreResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateKeyStoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateKeyStoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateKeyStoreResponse proto.InternalMessageInfo

type MsgUpdateKeyStore struct {
	Creator         string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	CosmosPublicKey string `protobuf:"bytes,2,opt,name=cosmosPublicKey,proto3" json:"cosmosPublicKey,omitempty"`
	MinaPublicKey   string `protobuf:"bytes,3,opt,name=minaPublicKey,proto3" json:"minaPublicKey,omitempty"`
	CosmosSignature []byte `protobuf:"bytes,4,opt,name=cosmosSignature,proto3" json:"cosmosSignature,omitempty"`
	MinaSignature   []byte `protobuf:"bytes,5,opt,name=minaSignature,proto3" json:"minaSignature,omitempty"`
}

func (m *MsgUpdateKeyStore) Reset()         { *m = MsgUpdateKeyStore{} }
func (m *MsgUpdateKeyStore) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateKeyStore) ProtoMessage()    {}
func (*MsgUpdateKeyStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e22f197626938e4, []int{4}
}
func (m *MsgUpdateKeyStore) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateKeyStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateKeyStore.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateKeyStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateKeyStore.Merge(m, src)
}
func (m *MsgUpdateKeyStore) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateKeyStore) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateKeyStore.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateKeyStore proto.InternalMessageInfo

func (m *MsgUpdateKeyStore) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateKeyStore) GetCosmosPublicKey() string {
	if m != nil {
		return m.CosmosPublicKey
	}
	return ""
}

func (m *MsgUpdateKeyStore) GetMinaPublicKey() string {
	if m != nil {
		return m.MinaPublicKey
	}
	return ""
}

func (m *MsgUpdateKeyStore) GetCosmosSignature() []byte {
	if m != nil {
		return m.CosmosSignature
	}
	return nil
}

func (m *MsgUpdateKeyStore) GetMinaSignature() []byte {
	if m != nil {
		return m.MinaSignature
	}
	return nil
}

type MsgUpdateKeyStoreResponse struct {
}

func (m *MsgUpdateKeyStoreResponse) Reset()         { *m = MsgUpdateKeyStoreResponse{} }
func (m *MsgUpdateKeyStoreResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateKeyStoreResponse) ProtoMessage()    {}
func (*MsgUpdateKeyStoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e22f197626938e4, []int{5}
}
func (m *MsgUpdateKeyStoreResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateKeyStoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateKeyStoreResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateKeyStoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateKeyStoreResponse.Merge(m, src)
}
func (m *MsgUpdateKeyStoreResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateKeyStoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateKeyStoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateKeyStoreResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "interchain_security.minakeys.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "interchain_security.minakeys.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgCreateKeyStore)(nil), "interchain_security.minakeys.MsgCreateKeyStore")
	proto.RegisterType((*MsgCreateKeyStoreResponse)(nil), "interchain_security.minakeys.MsgCreateKeyStoreResponse")
	proto.RegisterType((*MsgUpdateKeyStore)(nil), "interchain_security.minakeys.MsgUpdateKeyStore")
	proto.RegisterType((*MsgUpdateKeyStoreResponse)(nil), "interchain_security.minakeys.MsgUpdateKeyStoreResponse")
}

func init() {
	proto.RegisterFile("interchain_security/minakeys/tx.proto", fileDescriptor_9e22f197626938e4)
}

var fileDescriptor_9e22f197626938e4 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x54, 0xc1, 0x8b, 0xd3, 0x4e,
	0x14, 0xee, 0xec, 0xfe, 0x76, 0x7f, 0x74, 0xac, 0x2e, 0x1b, 0x16, 0x36, 0x8d, 0x12, 0x4b, 0x59,
	0xa1, 0x16, 0x9b, 0xb1, 0xbb, 0xa8, 0xb0, 0xb7, 0xad, 0x07, 0x0f, 0x4b, 0x61, 0x49, 0xf1, 0xe2,
	0xa5, 0x4c, 0xd3, 0x21, 0x1d, 0x76, 0x93, 0x09, 0x33, 0x13, 0xd9, 0x78, 0x12, 0x8f, 0x9e, 0xfc,
	0x33, 0x3c, 0xf6, 0xe0, 0x1f, 0xb1, 0xc7, 0x45, 0x10, 0x04, 0x41, 0xa4, 0x3d, 0xf4, 0x7f, 0xf0,
	0x24, 0xc9, 0x24, 0x64, 0x13, 0x4b, 0xb5, 0x57, 0x2f, 0x6d, 0xe6, 0x7b, 0xdf, 0xfb, 0xde, 0xfb,
	0x5e, 0xde, 0x04, 0x3e, 0xa0, 0xbe, 0x24, 0xdc, 0x99, 0x60, 0xea, 0x0f, 0x05, 0x71, 0x42, 0x4e,
	0x65, 0x84, 0x3c, 0xea, 0xe3, 0x73, 0x12, 0x09, 0x24, 0x2f, 0xad, 0x80, 0x33, 0xc9, 0xb4, 0x7b,
	0x4b, 0x68, 0x56, 0x46, 0x33, 0x76, 0xb1, 0x47, 0x7d, 0x86, 0x92, 0x5f, 0x95, 0x60, 0xec, 0x3b,
	0x4c, 0x78, 0x4c, 0x20, 0x4f, 0xb8, 0xe8, 0x75, 0x37, 0xfe, 0x4b, 0x03, 0x75, 0x15, 0x18, 0x26,
	0x27, 0xa4, 0x0e, 0x69, 0x68, 0xcf, 0x65, 0x2e, 0x53, 0x78, 0xfc, 0x94, 0xa2, 0x0f, 0x57, 0x76,
	0x18, 0x60, 0x8e, 0xbd, 0x4c, 0xe0, 0xd1, 0x4a, 0xea, 0x39, 0x89, 0x86, 0x42, 0x32, 0x4e, 0x14,
	0xbb, 0xf9, 0x05, 0xc0, 0x9d, 0xbe, 0x70, 0x5f, 0x06, 0x63, 0x2c, 0xc9, 0x59, 0xa2, 0xa3, 0x3d,
	0x85, 0x55, 0x1c, 0xca, 0x09, 0x8b, 0x33, 0x75, 0xd0, 0x00, 0xad, 0x6a, 0x4f, 0xff, 0xfc, 0xa9,
	0xb3, 0x97, 0xf6, 0x79, 0x32, 0x1e, 0x73, 0x22, 0xc4, 0x40, 0x72, 0xea, 0xbb, 0x76, 0x4e, 0xd5,
	0x5e, 0xc0, 0x6d, 0xd5, 0x89, 0xbe, 0xd1, 0x00, 0xad, 0x5b, 0x87, 0x07, 0xd6, 0xaa, 0x81, 0x59,
	0xaa, 0x5a, 0xaf, 0x7a, 0xf5, 0xfd, 0x7e, 0xe5, 0xe3, 0x62, 0xda, 0x06, 0x76, 0x9a, 0x7e, 0x7c,
	0xf2, 0x6e, 0x31, 0x6d, 0xe7, 0xc2, 0xef, 0x17, 0xd3, 0xf6, 0x32, 0x29, 0x74, 0x99, 0xfb, 0x2a,
	0x79, 0x68, 0xd6, 0xe1, 0x7e, 0x09, 0xb2, 0x89, 0x08, 0x98, 0x2f, 0x48, 0xf3, 0x1b, 0x80, 0xbb,
	0x7d, 0xe1, 0x3e, 0xe7, 0x04, 0x4b, 0x72, 0x4a, 0xa2, 0x41, 0x3c, 0x0e, 0x4d, 0x87, 0xff, 0x3b,
	0x31, 0xc2, 0xb8, 0xb2, 0x6c, 0x67, 0x47, 0xad, 0x05, 0x77, 0x94, 0xf3, 0xb3, 0x70, 0x74, 0x41,
	0x9d, 0x53, 0x12, 0x25, 0xfe, 0xaa, 0x76, 0x19, 0xd6, 0x0e, 0xe0, 0xed, 0xb8, 0xa1, 0x9c, 0xb7,
	0x99, 0xf0, 0x8a, 0x60, 0xae, 0x37, 0xa0, 0xae, 0x8f, 0x65, 0xc8, 0x89, 0xfe, 0x5f, 0x03, 0xb4,
	0x6a, 0x76, 0x19, 0xce, 0xf4, 0x72, 0xde, 0x56, 0xc2, 0x2b, 0x82, 0xc7, 0xb5, 0x78, 0x5a, 0x59,
	0xb7, 0xcd, 0xbb, 0xb0, 0xfe, 0x9b, 0xb9, 0xb2, 0x75, 0x35, 0x96, 0x7f, 0xd4, 0x7a, 0xd1, 0x5c,
	0x66, 0xfd, 0xf0, 0xe7, 0x06, 0xdc, 0xec, 0x0b, 0x57, 0x93, 0xb0, 0x56, 0x58, 0xf6, 0xce, 0xea,
	0x25, 0x2d, 0x2d, 0x91, 0xf1, 0x64, 0x2d, 0x7a, 0x56, 0x5d, 0x7b, 0x03, 0xef, 0x94, 0xf6, 0x0d,
	0xfd, 0x51, 0xa8, 0x98, 0x60, 0x3c, 0x5b, 0x33, 0xe1, 0x66, 0xed, 0xd2, 0x0b, 0x47, 0x7f, 0x69,
	0x62, 0x8d, 0xda, 0xcb, 0xa7, 0x6e, 0x6c, 0xbd, 0x8d, 0x2f, 0x76, 0xaf, 0x7f, 0x35, 0x33, 0xc1,
	0xf5, 0xcc, 0x04, 0x3f, 0x66, 0x26, 0xf8, 0x30, 0x37, 0x2b, 0xd7, 0x73, 0xb3, 0xf2, 0x75, 0x6e,
	0x56, 0x5e, 0x1d, 0xb9, 0x54, 0x4e, 0xc2, 0x91, 0xe5, 0x30, 0x0f, 0xf9, 0x6c, 0x4c, 0xba, 0x8f,
	0xbb, 0x1d, 0xca, 0x50, 0x10, 0x5e, 0x08, 0xcc, 0x51, 0x52, 0xf0, 0xe6, 0x35, 0x97, 0x51, 0x40,
	0xc4, 0x68, 0x3b, 0xf9, 0x76, 0x1d, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x14, 0x7f, 0xdf, 0xba,
	0xb8, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	CreateKeyStore(ctx context.Context, in *MsgCreateKeyStore, opts ...grpc.CallOption) (*MsgCreateKeyStoreResponse, error)
	UpdateKeyStore(ctx context.Context, in *MsgUpdateKeyStore, opts ...grpc.CallOption) (*MsgUpdateKeyStoreResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/interchain_security.minakeys.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateKeyStore(ctx context.Context, in *MsgCreateKeyStore, opts ...grpc.CallOption) (*MsgCreateKeyStoreResponse, error) {
	out := new(MsgCreateKeyStoreResponse)
	err := c.cc.Invoke(ctx, "/interchain_security.minakeys.Msg/CreateKeyStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateKeyStore(ctx context.Context, in *MsgUpdateKeyStore, opts ...grpc.CallOption) (*MsgUpdateKeyStoreResponse, error) {
	out := new(MsgUpdateKeyStoreResponse)
	err := c.cc.Invoke(ctx, "/interchain_security.minakeys.Msg/UpdateKeyStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	CreateKeyStore(context.Context, *MsgCreateKeyStore) (*MsgCreateKeyStoreResponse, error)
	UpdateKeyStore(context.Context, *MsgUpdateKeyStore) (*MsgUpdateKeyStoreResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) CreateKeyStore(ctx context.Context, req *MsgCreateKeyStore) (*MsgCreateKeyStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKeyStore not implemented")
}
func (*UnimplementedMsgServer) UpdateKeyStore(ctx context.Context, req *MsgUpdateKeyStore) (*MsgUpdateKeyStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKeyStore not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.minakeys.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateKeyStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateKeyStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateKeyStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.minakeys.Msg/CreateKeyStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateKeyStore(ctx, req.(*MsgCreateKeyStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateKeyStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateKeyStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateKeyStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.minakeys.Msg/UpdateKeyStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateKeyStore(ctx, req.(*MsgUpdateKeyStore))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "interchain_security.minakeys.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateKeyStore",
			Handler:    _Msg_CreateKeyStore_Handler,
		},
		{
			MethodName: "UpdateKeyStore",
			Handler:    _Msg_UpdateKeyStore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interchain_security/minakeys/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateKeyStore) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateKeyStore) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateKeyStore) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MinaSignature) > 0 {
		i -= len(m.MinaSignature)
		copy(dAtA[i:], m.MinaSignature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MinaSignature)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.CosmosSignature) > 0 {
		i -= len(m.CosmosSignature)
		copy(dAtA[i:], m.CosmosSignature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CosmosSignature)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MinaPublicKey) > 0 {
		i -= len(m.MinaPublicKey)
		copy(dAtA[i:], m.MinaPublicKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MinaPublicKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CosmosPublicKey) > 0 {
		i -= len(m.CosmosPublicKey)
		copy(dAtA[i:], m.CosmosPublicKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CosmosPublicKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateKeyStoreResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateKeyStoreResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateKeyStoreResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateKeyStore) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateKeyStore) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateKeyStore) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MinaSignature) > 0 {
		i -= len(m.MinaSignature)
		copy(dAtA[i:], m.MinaSignature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MinaSignature)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.CosmosSignature) > 0 {
		i -= len(m.CosmosSignature)
		copy(dAtA[i:], m.CosmosSignature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CosmosSignature)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MinaPublicKey) > 0 {
		i -= len(m.MinaPublicKey)
		copy(dAtA[i:], m.MinaPublicKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MinaPublicKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CosmosPublicKey) > 0 {
		i -= len(m.CosmosPublicKey)
		copy(dAtA[i:], m.CosmosPublicKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CosmosPublicKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateKeyStoreResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateKeyStoreResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateKeyStoreResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateKeyStore) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CosmosPublicKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MinaPublicKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CosmosSignature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MinaSignature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateKeyStoreResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateKeyStore) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CosmosPublicKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MinaPublicKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CosmosSignature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MinaSignature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateKeyStoreResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateKeyStore) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateKeyStore: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateKeyStore: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosmosPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinaPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinaPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosmosSignature = append(m.CosmosSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.CosmosSignature == nil {
				m.CosmosSignature = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinaSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinaSignature = append(m.MinaSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.MinaSignature == nil {
				m.MinaSignature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateKeyStoreResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateKeyStoreResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateKeyStoreResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateKeyStore) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateKeyStore: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateKeyStore: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosmosPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinaPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinaPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosmosSignature = append(m.CosmosSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.CosmosSignature == nil {
				m.CosmosSignature = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinaSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinaSignature = append(m.MinaSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.MinaSignature == nil {
				m.MinaSignature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateKeyStoreResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateKeyStoreResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateKeyStoreResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
