// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: interchain_security/bridge/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d28a7fdbf2c848e, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d28a7fdbf2c848e, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryTestRequest is request type for the Query/TestQuery RPC method.
type QueryTestRequest struct {
}

func (m *QueryTestRequest) Reset()         { *m = QueryTestRequest{} }
func (m *QueryTestRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTestRequest) ProtoMessage()    {}
func (*QueryTestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d28a7fdbf2c848e, []int{2}
}
func (m *QueryTestRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTestRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTestRequest.Merge(m, src)
}
func (m *QueryTestRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTestRequest proto.InternalMessageInfo

// QueryTestResponse is response type for the Query/TestQuery RPC method.
type QueryTestResponse struct {
	// result holds the test string
	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *QueryTestResponse) Reset()         { *m = QueryTestResponse{} }
func (m *QueryTestResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTestResponse) ProtoMessage()    {}
func (*QueryTestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d28a7fdbf2c848e, []int{3}
}
func (m *QueryTestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTestResponse.Merge(m, src)
}
func (m *QueryTestResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTestResponse proto.InternalMessageInfo

func (m *QueryTestResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type QueryAllDepositAmountMapRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDepositAmountMapRequest) Reset()         { *m = QueryAllDepositAmountMapRequest{} }
func (m *QueryAllDepositAmountMapRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllDepositAmountMapRequest) ProtoMessage()    {}
func (*QueryAllDepositAmountMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d28a7fdbf2c848e, []int{4}
}
func (m *QueryAllDepositAmountMapRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDepositAmountMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDepositAmountMapRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDepositAmountMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDepositAmountMapRequest.Merge(m, src)
}
func (m *QueryAllDepositAmountMapRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDepositAmountMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDepositAmountMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDepositAmountMapRequest proto.InternalMessageInfo

func (m *QueryAllDepositAmountMapRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllDepositAmountMapResponse struct {
	DepositAmountMap []DepositAmountMap  `protobuf:"bytes,1,rep,name=depositAmountMap,proto3" json:"depositAmountMap"`
	Pagination       *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDepositAmountMapResponse) Reset()         { *m = QueryAllDepositAmountMapResponse{} }
func (m *QueryAllDepositAmountMapResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllDepositAmountMapResponse) ProtoMessage()    {}
func (*QueryAllDepositAmountMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d28a7fdbf2c848e, []int{5}
}
func (m *QueryAllDepositAmountMapResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDepositAmountMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDepositAmountMapResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDepositAmountMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDepositAmountMapResponse.Merge(m, src)
}
func (m *QueryAllDepositAmountMapResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDepositAmountMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDepositAmountMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDepositAmountMapResponse proto.InternalMessageInfo

func (m *QueryAllDepositAmountMapResponse) GetDepositAmountMap() []DepositAmountMap {
	if m != nil {
		return m.DepositAmountMap
	}
	return nil
}

func (m *QueryAllDepositAmountMapResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetDepositAmountMapRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryGetDepositAmountMapRequest) Reset()         { *m = QueryGetDepositAmountMapRequest{} }
func (m *QueryGetDepositAmountMapRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDepositAmountMapRequest) ProtoMessage()    {}
func (*QueryGetDepositAmountMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d28a7fdbf2c848e, []int{6}
}
func (m *QueryGetDepositAmountMapRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDepositAmountMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDepositAmountMapRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDepositAmountMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDepositAmountMapRequest.Merge(m, src)
}
func (m *QueryGetDepositAmountMapRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDepositAmountMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDepositAmountMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDepositAmountMapRequest proto.InternalMessageInfo

func (m *QueryGetDepositAmountMapRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryGetDepositAmountMapResponse struct {
	DepositAmountMap DepositAmountMap `protobuf:"bytes,1,opt,name=depositAmountMap,proto3" json:"depositAmountMap"`
}

func (m *QueryGetDepositAmountMapResponse) Reset()         { *m = QueryGetDepositAmountMapResponse{} }
func (m *QueryGetDepositAmountMapResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDepositAmountMapResponse) ProtoMessage()    {}
func (*QueryGetDepositAmountMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d28a7fdbf2c848e, []int{7}
}
func (m *QueryGetDepositAmountMapResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDepositAmountMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDepositAmountMapResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDepositAmountMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDepositAmountMapResponse.Merge(m, src)
}
func (m *QueryGetDepositAmountMapResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDepositAmountMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDepositAmountMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDepositAmountMapResponse proto.InternalMessageInfo

func (m *QueryGetDepositAmountMapResponse) GetDepositAmountMap() DepositAmountMap {
	if m != nil {
		return m.DepositAmountMap
	}
	return DepositAmountMap{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "interchain_security.bridge.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "interchain_security.bridge.QueryParamsResponse")
	proto.RegisterType((*QueryTestRequest)(nil), "interchain_security.bridge.QueryTestRequest")
	proto.RegisterType((*QueryTestResponse)(nil), "interchain_security.bridge.QueryTestResponse")
	proto.RegisterType((*QueryAllDepositAmountMapRequest)(nil), "interchain_security.bridge.QueryAllDepositAmountMapRequest")
	proto.RegisterType((*QueryAllDepositAmountMapResponse)(nil), "interchain_security.bridge.QueryAllDepositAmountMapResponse")
	proto.RegisterType((*QueryGetDepositAmountMapRequest)(nil), "interchain_security.bridge.QueryGetDepositAmountMapRequest")
	proto.RegisterType((*QueryGetDepositAmountMapResponse)(nil), "interchain_security.bridge.QueryGetDepositAmountMapResponse")
}

func init() {
	proto.RegisterFile("interchain_security/bridge/query.proto", fileDescriptor_6d28a7fdbf2c848e)
}

var fileDescriptor_6d28a7fdbf2c848e = []byte{
	// 611 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcf, 0x6a, 0x13, 0x41,
	0x18, 0xcf, 0x54, 0x1b, 0xe9, 0xf4, 0xd2, 0x4e, 0x8b, 0x94, 0x45, 0xb6, 0x61, 0x91, 0x36, 0xc4,
	0x76, 0xc7, 0xa6, 0xf8, 0x07, 0xeb, 0xc1, 0x04, 0xb5, 0x27, 0xa1, 0x0d, 0x9e, 0x44, 0x0c, 0x93,
	0x64, 0xd8, 0x0e, 0xec, 0xee, 0x6c, 0x77, 0x66, 0x8b, 0x41, 0xbc, 0xf4, 0x09, 0x44, 0xf1, 0x1d,
	0x3c, 0xfa, 0x18, 0x01, 0x0f, 0x56, 0xbc, 0x78, 0x12, 0x49, 0x04, 0x5f, 0x43, 0x76, 0x66, 0xd2,
	0x26, 0x69, 0xb3, 0x49, 0xc5, 0x4b, 0xd8, 0x9d, 0xfd, 0x7d, 0xdf, 0xef, 0xcf, 0x7c, 0x33, 0x81,
	0x6b, 0x2c, 0x94, 0x34, 0x6e, 0x1e, 0x10, 0x16, 0xd6, 0x05, 0x6d, 0x26, 0x31, 0x93, 0x6d, 0xdc,
	0x88, 0x59, 0xcb, 0xa3, 0xf8, 0x30, 0xa1, 0x71, 0xdb, 0x8d, 0x62, 0x2e, 0x39, 0xb2, 0x2e, 0xc0,
	0xb9, 0x1a, 0x67, 0x2d, 0x92, 0x80, 0x85, 0x1c, 0xab, 0x5f, 0x0d, 0xb7, 0x96, 0x3d, 0xee, 0x71,
	0xf5, 0x88, 0xd3, 0x27, 0xb3, 0x7a, 0xc3, 0xe3, 0xdc, 0xf3, 0x29, 0x26, 0x11, 0xc3, 0x24, 0x0c,
	0xb9, 0x24, 0x92, 0xf1, 0x50, 0x98, 0xaf, 0xa5, 0x26, 0x17, 0x01, 0x17, 0xb8, 0x41, 0x84, 0xe1,
	0xc6, 0x47, 0x5b, 0x0d, 0x2a, 0xc9, 0x16, 0x8e, 0x88, 0xc7, 0x42, 0x05, 0x36, 0xd8, 0xf5, 0x0c,
	0xd9, 0x11, 0x89, 0x49, 0xd0, 0x6f, 0xba, 0x9d, 0x01, 0x6c, 0xd1, 0x88, 0x0b, 0x26, 0xeb, 0x24,
	0xe0, 0x49, 0x28, 0xeb, 0x01, 0x89, 0x74, 0x91, 0xb3, 0x0c, 0xd1, 0x7e, 0xca, 0xbf, 0xa7, 0x3a,
	0xd5, 0xe8, 0x61, 0x42, 0x85, 0x74, 0x5e, 0xc2, 0xa5, 0xa1, 0x55, 0x11, 0xf1, 0x50, 0x50, 0xf4,
	0x04, 0xe6, 0x35, 0xe3, 0x0a, 0x28, 0x80, 0xe2, 0x7c, 0xd9, 0x71, 0xc7, 0x47, 0xe5, 0xea, 0xda,
	0xea, 0x5c, 0xe7, 0xe7, 0x6a, 0xee, 0xd3, 0x9f, 0xcf, 0x25, 0x50, 0x33, 0xc5, 0x0e, 0x82, 0x0b,
	0xaa, 0xfb, 0x73, 0x2a, 0x64, 0x9f, 0xf1, 0x16, 0x5c, 0x1c, 0x58, 0x33, 0x7c, 0xd7, 0x61, 0x3e,
	0xa6, 0x22, 0xf1, 0xa5, 0xe2, 0x9b, 0xab, 0x99, 0x37, 0x87, 0xc1, 0x55, 0x05, 0xae, 0xf8, 0xfe,
	0x63, 0x6d, 0xac, 0xa2, 0x7c, 0x3d, 0x23, 0x91, 0xe9, 0x87, 0x9e, 0x42, 0x78, 0x96, 0xa4, 0x91,
	0xbb, 0xe6, 0xea, 0xd8, 0xdd, 0x34, 0x76, 0x57, 0x6f, 0xb9, 0x89, 0xdd, 0xdd, 0x23, 0x1e, 0x35,
	0xb5, 0xb5, 0x81, 0x4a, 0xe7, 0x0b, 0x80, 0x85, 0xf1, 0x5c, 0x46, 0xe7, 0x2b, 0xb8, 0xd0, 0x1a,
	0xf9, 0xb6, 0x02, 0x0a, 0x57, 0x8a, 0xf3, 0xe5, 0x8d, 0xac, 0x84, 0x46, 0xfb, 0x55, 0xaf, 0xa6,
	0x59, 0xd5, 0xce, 0xf5, 0x42, 0xbb, 0x43, 0x66, 0x66, 0x94, 0x99, 0xf5, 0x89, 0x66, 0xb4, 0xb8,
	0x21, 0x37, 0x3b, 0x26, 0xb8, 0x5d, 0x2a, 0xc7, 0x05, 0xb7, 0x02, 0xaf, 0x91, 0x56, 0x2b, 0xa6,
	0x42, 0x98, 0xd0, 0xfb, 0xaf, 0xce, 0x71, 0x3f, 0x8a, 0x0b, 0xab, 0x33, 0xa3, 0x00, 0xff, 0x2b,
	0x8a, 0xf2, 0xb7, 0x59, 0x38, 0xab, 0x44, 0xa0, 0x8f, 0x00, 0xe6, 0xf5, 0x8c, 0x21, 0x37, 0xab,
	0xf5, 0xf9, 0xf1, 0xb6, 0xf0, 0xd4, 0x78, 0xed, 0xca, 0x29, 0x1d, 0x7f, 0xff, 0xfd, 0x61, 0xe6,
	0x26, 0x72, 0xf0, 0xc4, 0xc3, 0x88, 0xde, 0x03, 0x38, 0x97, 0x4e, 0xb1, 0x56, 0xb9, 0x31, 0x91,
	0x6a, 0xe0, 0x14, 0x58, 0x9b, 0x53, 0xa2, 0x8d, 0xac, 0xa2, 0x92, 0xe5, 0xa0, 0x42, 0x96, 0x2c,
	0x99, 0xee, 0x6a, 0x07, 0xc0, 0xa5, 0xd1, 0x8c, 0x2b, 0xbe, 0x8f, 0x76, 0x26, 0x12, 0x8e, 0x3f,
	0x63, 0xd6, 0xc3, 0x7f, 0x2b, 0x36, 0xe2, 0xef, 0x2a, 0xf1, 0xb7, 0x91, 0x8b, 0x2f, 0x75, 0x6f,
	0xa1, 0xaf, 0x00, 0x2e, 0x8c, 0x36, 0x9d, 0xc2, 0xc7, 0xf8, 0x91, 0x9f, 0xc2, 0x47, 0xc6, 0xc4,
	0x3b, 0x8f, 0x94, 0x8f, 0x07, 0xe8, 0xfe, 0xe5, 0x7c, 0xe0, 0x37, 0xe6, 0x5c, 0xbd, 0xad, 0xee,
	0x77, 0xba, 0x36, 0x38, 0xe9, 0xda, 0xe0, 0x57, 0xd7, 0x06, 0xef, 0x7a, 0x76, 0xee, 0xa4, 0x67,
	0xe7, 0x7e, 0xf4, 0xec, 0xdc, 0x8b, 0x7b, 0x1e, 0x93, 0x07, 0x49, 0xc3, 0x6d, 0xf2, 0x00, 0x9b,
	0xbf, 0x8c, 0x33, 0x92, 0xcd, 0x53, 0x92, 0xa3, 0x3b, 0xf8, 0xf5, 0xe9, 0x76, 0xb7, 0x23, 0x2a,
	0x1a, 0x79, 0x75, 0xbb, 0x6f, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x35, 0xf3, 0x73, 0x76, 0xf4,
	0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// TestQuery returns a test string "node101"
	TestQuery(ctx context.Context, in *QueryTestRequest, opts ...grpc.CallOption) (*QueryTestResponse, error)
	// Queries a list of DepositAmountMap items.
	DepositAmountMapAll(ctx context.Context, in *QueryAllDepositAmountMapRequest, opts ...grpc.CallOption) (*QueryAllDepositAmountMapResponse, error)
	// Queries a DepositAmountMap by address.
	DepositAmountMap(ctx context.Context, in *QueryGetDepositAmountMapRequest, opts ...grpc.CallOption) (*QueryGetDepositAmountMapResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/interchain_security.bridge.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TestQuery(ctx context.Context, in *QueryTestRequest, opts ...grpc.CallOption) (*QueryTestResponse, error) {
	out := new(QueryTestResponse)
	err := c.cc.Invoke(ctx, "/interchain_security.bridge.Query/TestQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DepositAmountMapAll(ctx context.Context, in *QueryAllDepositAmountMapRequest, opts ...grpc.CallOption) (*QueryAllDepositAmountMapResponse, error) {
	out := new(QueryAllDepositAmountMapResponse)
	err := c.cc.Invoke(ctx, "/interchain_security.bridge.Query/DepositAmountMapAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DepositAmountMap(ctx context.Context, in *QueryGetDepositAmountMapRequest, opts ...grpc.CallOption) (*QueryGetDepositAmountMapResponse, error) {
	out := new(QueryGetDepositAmountMapResponse)
	err := c.cc.Invoke(ctx, "/interchain_security.bridge.Query/DepositAmountMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// TestQuery returns a test string "node101"
	TestQuery(context.Context, *QueryTestRequest) (*QueryTestResponse, error)
	// Queries a list of DepositAmountMap items.
	DepositAmountMapAll(context.Context, *QueryAllDepositAmountMapRequest) (*QueryAllDepositAmountMapResponse, error)
	// Queries a DepositAmountMap by address.
	DepositAmountMap(context.Context, *QueryGetDepositAmountMapRequest) (*QueryGetDepositAmountMapResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) TestQuery(ctx context.Context, req *QueryTestRequest) (*QueryTestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestQuery not implemented")
}
func (*UnimplementedQueryServer) DepositAmountMapAll(ctx context.Context, req *QueryAllDepositAmountMapRequest) (*QueryAllDepositAmountMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositAmountMapAll not implemented")
}
func (*UnimplementedQueryServer) DepositAmountMap(ctx context.Context, req *QueryGetDepositAmountMapRequest) (*QueryGetDepositAmountMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositAmountMap not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.bridge.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TestQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TestQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.bridge.Query/TestQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TestQuery(ctx, req.(*QueryTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DepositAmountMapAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDepositAmountMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DepositAmountMapAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.bridge.Query/DepositAmountMapAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DepositAmountMapAll(ctx, req.(*QueryAllDepositAmountMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DepositAmountMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDepositAmountMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DepositAmountMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.bridge.Query/DepositAmountMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DepositAmountMap(ctx, req.(*QueryGetDepositAmountMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "interchain_security.bridge.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "TestQuery",
			Handler:    _Query_TestQuery_Handler,
		},
		{
			MethodName: "DepositAmountMapAll",
			Handler:    _Query_DepositAmountMapAll_Handler,
		},
		{
			MethodName: "DepositAmountMap",
			Handler:    _Query_DepositAmountMap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interchain_security/bridge/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryTestRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTestRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTestRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Result) > 0 {
		i -= len(m.Result)
		copy(dAtA[i:], m.Result)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Result)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDepositAmountMapRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDepositAmountMapRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDepositAmountMapRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDepositAmountMapResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDepositAmountMapResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDepositAmountMapResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.DepositAmountMap) > 0 {
		for iNdEx := len(m.DepositAmountMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DepositAmountMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDepositAmountMapRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDepositAmountMapRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDepositAmountMapRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDepositAmountMapResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDepositAmountMapResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDepositAmountMapResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.DepositAmountMap.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryTestRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDepositAmountMapRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDepositAmountMapResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DepositAmountMap) > 0 {
		for _, e := range m.DepositAmountMap {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDepositAmountMapRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDepositAmountMapResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DepositAmountMap.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTestRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTestRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTestRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDepositAmountMapRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDepositAmountMapRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDepositAmountMapRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDepositAmountMapResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDepositAmountMapResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDepositAmountMapResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositAmountMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositAmountMap = append(m.DepositAmountMap, DepositAmountMap{})
			if err := m.DepositAmountMap[len(m.DepositAmountMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDepositAmountMapRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDepositAmountMapRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDepositAmountMapRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDepositAmountMapResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDepositAmountMapResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDepositAmountMapResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositAmountMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DepositAmountMap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
