services:
    redis:
        image: redis:7-alpine
        networks: [pulsar-net]
        restart: unless-stopped
        volumes:
            - redis-data:/data
        ports:
            - "6379:6379"
        command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
        env_file:
            - .env
        # healthcheck:
        #     test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
        #     interval: 10s
        #     retries: 5

    mongo:
        image: mongo:7-jammy
        networks: [pulsar-net]
        restart: unless-stopped
        environment:
            DOCKER: "1"
            MONGO_INITDB_DATABASE: ${MONGO_DB}
        volumes:
            - mongo-data:/data/db
        ports:
            - "27017:27017"
        # networks: [pulsar-net]
        # healthcheck:
        #     test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
        #     interval: 10s
        #     retries: 5

    node-manager:
        build:
            context: .
            dockerfile: Dockerfile
        networks: [pulsar-net]
        env_file: .env
        environment:
            DOCKER: "1"
            WORKER: settlementWorker
            MINA_PRIVATE_KEY: ${MINA_PRIVATE_KEY}
            MINA_NETWORK: ${MINA_NETWORK}
            FEE: ${FEE}
            CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
            PULSAR_RPC_ADDRESS: mock-pulsar:50051
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            MONGO_URI: mongodb://mongo:27017/${MONGO_DB}
            MONGO_DB: ${MONGO_DB}
        entrypoint: ["node", "dist/src/nodeManager.js"]
        restart: always
        depends_on: [redis, mongo, mock-pulsar, mina-local-lightnet]
        profiles: ["app"]

    settlement-worker:
        build:
            context: .
            dockerfile: Dockerfile
        networks: [pulsar-net]
        env_file: .env
        environment:
            DOCKER: "1"
            WORKER: settlementWorker
            MINA_PRIVATE_KEY: ${MINA_PRIVATE_KEY}
            MINA_NETWORK: ${MINA_NETWORK}
            FEE: ${FEE}
            CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            MONGO_URI: mongodb://mongo:27017/${MONGO_DB}
            MONGO_DB: ${MONGO_DB}
        restart: always
        depends_on: [redis, mongo, node-manager]
        profiles: ["app"]
        # deploy:
        #     resources:
        #         limits:
        #             memory: 3g
        # healthcheck:
        #     test: ["CMD", "wget", "-qO-", "http://localhost:8081/healthz"]
        #     interval: 30s
        #     retries: 3

    reduce-worker:
        extends: settlement-worker
        environment:
            WORKER: reduceWorker
        profiles: ["app"]

    merge-worker:
        extends: settlement-worker
        environment:
            WORKER: mergeWorker
        profiles: ["app"]

    collect-worker:
        extends: settlement-worker
        environment:
            WORKER: collectWorker
        profiles: ["app"]

    mock-pulsar:
        build:
            context: .
            dockerfile: Dockerfile.mock-pulsar
        environment:
            - NODE_ENV=development
        ports:
            - "50051:50051"
        networks: [pulsar-net]
        profiles: ["app"]
        # healthcheck:
        # test: ["CMD", "grpc_health_probe", "-addr=localhost:50051"]
        # interval: 10s
        # retries: 3

    mina-local-lightnet:
        image: o1labs/mina-local-network:compatible-latest-lightnet
        environment:
            NETWORK_TYPE: "single-node"
            PROOF_LEVEL: "none"
            LOG_LEVEL: "Trace"
            RUN_ARCHIVE_NODE: false
            SLOT_TIME: 20000
        networks: [pulsar-net]
        ports:
            - "8080:8080"
            - "8282:8282"
            - "3085:3085"
            - "5432:5432"
            - "8181:8181"
        profiles: ["app"]
        # healthcheck:
        #     test: ["CMD", "wget", "-qO-", "http://localhost:8080/graphql"]
        #     interval: 10s
        #     retries: 5

volumes:
    redis-data:
    mongo-data:

networks:
    pulsar-net:
