version: "3.9"

services:
    redis:
        image: redis:7-alpine
        restart: unless-stopped
        volumes:
            - redis-data:/data
        ports:
            - "6379:6379"

    mongo:
        image: mongo:7-jammy
        restart: unless-stopped
        environment:
            MONGO_INITDB_DATABASE: pulsar
        volumes:
            - mongo-data:/data/db
        ports:
            - "27017:27017"

    # orchestrator:
    #     build: .
    #     depends_on: [redis, mongo]
    #     env_file: .env
    #     restart: unless-stopped

    # settlement-worker:
    #     build: .
    #     command: ["node", "dist/src/workers/settlementWorker.js"]
    #     depends_on: [redis, mongo]
    #     env_file: .env
    #     restart: unless-stopped

    # reducer-worker:
    #     build: .
    #     command: ["node", "dist/src/workers/reducerWorker.js"]
    #     depends_on: [redis, mongo]
    #     env_file: .env
    #     restart: unless-stopped

volumes:
    redis-data:
    mongo-data:
