services:
    redis:
        image: redis:7-alpine
        networks: [pulsar-net]
        restart: unless-stopped
        volumes:
            - redis-data:/data
        ports:
            - "6379:6379"
        command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
        env_file:
            - .env

    mongo:
        image: mongo:7-jammy
        networks: [pulsar-net]
        restart: unless-stopped
        environment:
            DOCKER: "1"
            MONGO_INITDB_DATABASE: ${MONGO_DB}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        volumes:
            - mongo-data:/data/db
        expose:
            - 27017

    node-manager:
        # image: kadirchan/pulsar-prover-node:latest
        build:
            context: .
            dockerfile: Dockerfile
        networks: [pulsar-net]
        env_file: .env
        environment:
            DOCKER: "1"
            WORKER: settlementWorker
            MINA_PRIVATE_KEY: ${MINA_PRIVATE_KEY}
            MINA_NETWORK: ${MINA_NETWORK}
            FEE: ${FEE}
            CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
            PULSAR_RPC_ADDRESS: mock-pulsar:50051
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            MONGO_URI: ${MONGO_URI}
            MONGO_INITDB_DATABASE: ${MONGO_DB}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        entrypoint: ["node", "dist/src/nodeManager.js"]
        restart: always
        depends_on: [redis, mongo, mock-pulsar, mina-local-lightnet]
        profiles: ["mock-pulsar", "full-mock", "prod"]

    settlement-worker:
        # image: kadirchan/pulsar-prover-node:latest
        build:
            context: .
            dockerfile: Dockerfile
        networks: [pulsar-net]
        env_file: .env
        environment:
            DOCKER: "1"
            WORKER: settlementWorker
            MINA_PRIVATE_KEY: ${MINA_PRIVATE_KEY}
            MINA_NETWORK: ${MINA_NETWORK}
            FEE: ${FEE}
            CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            MONGO_URI: ${MONGO_URI}
            MONGO_INITDB_DATABASE: ${MONGO_DB}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        restart: always
        depends_on: [redis, mongo, node-manager, mock-pulsar, mina-local-lightnet]
        profiles: ["mock-pulsar", "full-mock", "prod"]

    reduce-worker:
        extends: settlement-worker
        environment:
            WORKER: reduceWorker
        profiles: ["mock-pulsar", "full-mock", "prod"]

    merge-worker:
        extends: settlement-worker
        environment:
            WORKER: mergeWorker
        profiles: ["mock-pulsar", "full-mock", "prod"]

    collect-worker:
        extends: settlement-worker
        environment:
            WORKER: collectWorker
        profiles: ["mock-pulsar", "full-mock", "prod"]

    mock-pulsar:
        build:
            context: .
            dockerfile: Dockerfile.mock-pulsar
        environment:
            - NODE_ENV=development
        ports:
            - "50051:50051"
        networks: [pulsar-net]
        profiles: ["mock-pulsar", "full-mock"]

    mina-local-lightnet:
        image: o1labs/mina-local-network:compatible-latest-lightnet
        environment:
            NETWORK_TYPE: "single-node"
            PROOF_LEVEL: "none"
            LOG_LEVEL: "Trace"
            RUN_ARCHIVE_NODE: false
            SLOT_TIME: 20000
        networks: [pulsar-net]
        ports:
            - "8080:8080"
            - "8282:8282"
            - "3085:3085"
            - "5432:5432"
            - "8181:8181"
        profiles: ["mock-pulsar", "full-mock"]

    mock-contract:
        build:
            context: .
            dockerfile: Dockerfile.mock-contract
        networks: [pulsar-net]
        env_file: .env
        environment:
            DOCKER: "1"
            MINA_NETWORK: ${MINA_NETWORK}
            MINA_PRIVATE_KEY: ${MINA_PRIVATE_KEY}
            CONTRACT_PRIVATE_KEY: ${CONTRACT_PRIVATE_KEY}
        depends_on: [mina-local-lightnet]
        profiles: ["mock-pulsar", "full-mock"]

volumes:
    redis-data:
    mongo-data:

networks:
    pulsar-net:
