// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package minakeys

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_TxTypeExtension         protoreflect.MessageDescriptor
	fd_TxTypeExtension_tx_type protoreflect.FieldDescriptor
)

func init() {
	file_cosmos_minakeys_tx_type_proto_init()
	md_TxTypeExtension = File_cosmos_minakeys_tx_type_proto.Messages().ByName("TxTypeExtension")
	fd_TxTypeExtension_tx_type = md_TxTypeExtension.Fields().ByName("tx_type")
}

var _ protoreflect.Message = (*fastReflection_TxTypeExtension)(nil)

type fastReflection_TxTypeExtension TxTypeExtension

func (x *TxTypeExtension) ProtoReflect() protoreflect.Message {
	return (*fastReflection_TxTypeExtension)(x)
}

func (x *TxTypeExtension) slowProtoReflect() protoreflect.Message {
	mi := &file_cosmos_minakeys_tx_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_TxTypeExtension_messageType fastReflection_TxTypeExtension_messageType
var _ protoreflect.MessageType = fastReflection_TxTypeExtension_messageType{}

type fastReflection_TxTypeExtension_messageType struct{}

func (x fastReflection_TxTypeExtension_messageType) Zero() protoreflect.Message {
	return (*fastReflection_TxTypeExtension)(nil)
}
func (x fastReflection_TxTypeExtension_messageType) New() protoreflect.Message {
	return new(fastReflection_TxTypeExtension)
}
func (x fastReflection_TxTypeExtension_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_TxTypeExtension
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_TxTypeExtension) Descriptor() protoreflect.MessageDescriptor {
	return md_TxTypeExtension
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_TxTypeExtension) Type() protoreflect.MessageType {
	return _fastReflection_TxTypeExtension_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_TxTypeExtension) New() protoreflect.Message {
	return new(fastReflection_TxTypeExtension)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_TxTypeExtension) Interface() protoreflect.ProtoMessage {
	return (*TxTypeExtension)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_TxTypeExtension) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.TxType != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.TxType))
		if !f(fd_TxTypeExtension_tx_type, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_TxTypeExtension) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "cosmos.minakeys.TxTypeExtension.tx_type":
		return x.TxType != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmos.minakeys.TxTypeExtension"))
		}
		panic(fmt.Errorf("message cosmos.minakeys.TxTypeExtension does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_TxTypeExtension) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "cosmos.minakeys.TxTypeExtension.tx_type":
		x.TxType = 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmos.minakeys.TxTypeExtension"))
		}
		panic(fmt.Errorf("message cosmos.minakeys.TxTypeExtension does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_TxTypeExtension) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "cosmos.minakeys.TxTypeExtension.tx_type":
		value := x.TxType
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmos.minakeys.TxTypeExtension"))
		}
		panic(fmt.Errorf("message cosmos.minakeys.TxTypeExtension does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_TxTypeExtension) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "cosmos.minakeys.TxTypeExtension.tx_type":
		x.TxType = (TxType)(value.Enum())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmos.minakeys.TxTypeExtension"))
		}
		panic(fmt.Errorf("message cosmos.minakeys.TxTypeExtension does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_TxTypeExtension) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "cosmos.minakeys.TxTypeExtension.tx_type":
		panic(fmt.Errorf("field tx_type of message cosmos.minakeys.TxTypeExtension is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmos.minakeys.TxTypeExtension"))
		}
		panic(fmt.Errorf("message cosmos.minakeys.TxTypeExtension does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_TxTypeExtension) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "cosmos.minakeys.TxTypeExtension.tx_type":
		return protoreflect.ValueOfEnum(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmos.minakeys.TxTypeExtension"))
		}
		panic(fmt.Errorf("message cosmos.minakeys.TxTypeExtension does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_TxTypeExtension) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in cosmos.minakeys.TxTypeExtension", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_TxTypeExtension) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_TxTypeExtension) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_TxTypeExtension) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_TxTypeExtension) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*TxTypeExtension)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.TxType != 0 {
			n += 1 + runtime.Sov(uint64(x.TxType))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*TxTypeExtension)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.TxType != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.TxType))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*TxTypeExtension)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: TxTypeExtension: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: TxTypeExtension: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TxType", wireType)
				}
				x.TxType = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.TxType |= TxType(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: cosmos/minakeys/tx_type.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TxType defines the type of transaction for signature verification
type TxType int32

const (
	// Default Cosmos SDK transaction
	TxType_COSMOS_TX TxType = 0
	// Mina wallet transaction
	TxType_MINA_TX TxType = 1
)

// Enum value maps for TxType.
var (
	TxType_name = map[int32]string{
		0: "COSMOS_TX",
		1: "MINA_TX",
	}
	TxType_value = map[string]int32{
		"COSMOS_TX": 0,
		"MINA_TX":   1,
	}
)

func (x TxType) Enum() *TxType {
	p := new(TxType)
	*p = x
	return p
}

func (x TxType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxType) Descriptor() protoreflect.EnumDescriptor {
	return file_cosmos_minakeys_tx_type_proto_enumTypes[0].Descriptor()
}

func (TxType) Type() protoreflect.EnumType {
	return &file_cosmos_minakeys_tx_type_proto_enumTypes[0]
}

func (x TxType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxType.Descriptor instead.
func (TxType) EnumDescriptor() ([]byte, []int) {
	return file_cosmos_minakeys_tx_type_proto_rawDescGZIP(), []int{0}
}

// TxTypeExtension is used as extension option to specify transaction type
type TxTypeExtension struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxType TxType `protobuf:"varint,1,opt,name=tx_type,json=txType,proto3,enum=cosmos.minakeys.TxType" json:"tx_type,omitempty"`
}

func (x *TxTypeExtension) Reset() {
	*x = TxTypeExtension{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmos_minakeys_tx_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxTypeExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxTypeExtension) ProtoMessage() {}

// Deprecated: Use TxTypeExtension.ProtoReflect.Descriptor instead.
func (*TxTypeExtension) Descriptor() ([]byte, []int) {
	return file_cosmos_minakeys_tx_type_proto_rawDescGZIP(), []int{0}
}

func (x *TxTypeExtension) GetTxType() TxType {
	if x != nil {
		return x.TxType
	}
	return TxType_COSMOS_TX
}

var File_cosmos_minakeys_tx_type_proto protoreflect.FileDescriptor

var file_cosmos_minakeys_tx_type_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x6d, 0x69, 0x6e, 0x61, 0x6b, 0x65, 0x79,
	0x73, 0x2f, 0x74, 0x78, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x6d, 0x69, 0x6e, 0x61, 0x6b, 0x65, 0x79, 0x73,
	0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x49, 0x0a, 0x0f, 0x54, 0x78, 0x54, 0x79, 0x70, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x6d,
	0x69, 0x6e, 0x61, 0x6b, 0x65, 0x79, 0x73, 0x2e, 0x54, 0x78, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06,
	0x74, 0x78, 0x54, 0x79, 0x70, 0x65, 0x3a, 0x04, 0x88, 0xa0, 0x1f, 0x00, 0x2a, 0x2a, 0x0a, 0x06,
	0x54, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x53, 0x4d, 0x4f, 0x53,
	0x5f, 0x54, 0x58, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x49, 0x4e, 0x41, 0x5f, 0x54, 0x58,
	0x10, 0x01, 0x1a, 0x04, 0x88, 0xa3, 0x1e, 0x00, 0x42, 0x9b, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d,
	0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x6d, 0x69, 0x6e, 0x61, 0x6b, 0x65, 0x79, 0x73,
	0x42, 0x0b, 0x54, 0x78, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x1a, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x2f, 0x6d, 0x69, 0x6e, 0x61, 0x6b, 0x65, 0x79, 0x73, 0xa2, 0x02, 0x03, 0x43, 0x4d,
	0x58, 0xaa, 0x02, 0x0f, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x4d, 0x69, 0x6e, 0x61, 0x6b,
	0x65, 0x79, 0x73, 0xca, 0x02, 0x0f, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x5c, 0x4d, 0x69, 0x6e,
	0x61, 0x6b, 0x65, 0x79, 0x73, 0xe2, 0x02, 0x1b, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x5c, 0x4d,
	0x69, 0x6e, 0x61, 0x6b, 0x65, 0x79, 0x73, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x10, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x3a, 0x3a, 0x4d, 0x69,
	0x6e, 0x61, 0x6b, 0x65, 0x79, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cosmos_minakeys_tx_type_proto_rawDescOnce sync.Once
	file_cosmos_minakeys_tx_type_proto_rawDescData = file_cosmos_minakeys_tx_type_proto_rawDesc
)

func file_cosmos_minakeys_tx_type_proto_rawDescGZIP() []byte {
	file_cosmos_minakeys_tx_type_proto_rawDescOnce.Do(func() {
		file_cosmos_minakeys_tx_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_cosmos_minakeys_tx_type_proto_rawDescData)
	})
	return file_cosmos_minakeys_tx_type_proto_rawDescData
}

var file_cosmos_minakeys_tx_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cosmos_minakeys_tx_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cosmos_minakeys_tx_type_proto_goTypes = []interface{}{
	(TxType)(0),             // 0: cosmos.minakeys.TxType
	(*TxTypeExtension)(nil), // 1: cosmos.minakeys.TxTypeExtension
}
var file_cosmos_minakeys_tx_type_proto_depIdxs = []int32{
	0, // 0: cosmos.minakeys.TxTypeExtension.tx_type:type_name -> cosmos.minakeys.TxType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cosmos_minakeys_tx_type_proto_init() }
func file_cosmos_minakeys_tx_type_proto_init() {
	if File_cosmos_minakeys_tx_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cosmos_minakeys_tx_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxTypeExtension); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cosmos_minakeys_tx_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cosmos_minakeys_tx_type_proto_goTypes,
		DependencyIndexes: file_cosmos_minakeys_tx_type_proto_depIdxs,
		EnumInfos:         file_cosmos_minakeys_tx_type_proto_enumTypes,
		MessageInfos:      file_cosmos_minakeys_tx_type_proto_msgTypes,
	}.Build()
	File_cosmos_minakeys_tx_type_proto = out.File
	file_cosmos_minakeys_tx_type_proto_rawDesc = nil
	file_cosmos_minakeys_tx_type_proto_goTypes = nil
	file_cosmos_minakeys_tx_type_proto_depIdxs = nil
}
