export {
  VALIDATOR_NUMBER,
  AGGREGATE_THRESHOLD,
  TOTAL_GENERATORS,
  LIST_LENGTH,
  MINIMUM_DEPOSIT_AMOUNT,
  WITHDRAW_DOWN_PAYMENT,
  BATCH_SIZE,
};

const VALIDATOR_NUMBER = 60;
const AGGREGATE_THRESHOLD = 32;
const LIST_LENGTH = AGGREGATE_THRESHOLD;
const TOTAL_GENERATORS = LIST_LENGTH - 1;
const MINIMUM_DEPOSIT_AMOUNT = 1e9;
const WITHDRAW_DOWN_PAYMENT = 1e10;
const BATCH_SIZE = 10;
