export {
  VALIDATOR_NUMBER,
  AGGREGATE_THRESHOLD,
  TOTAL_GENERATORS,
  LIST_LENGTH,
  MINIMUM_DEPOSIT_AMOUNT,
};

const VALIDATOR_NUMBER = 60;
const AGGREGATE_THRESHOLD = 32;
const LIST_LENGTH = AGGREGATE_THRESHOLD;
const TOTAL_GENERATORS = LIST_LENGTH - 1;
const MINIMUM_DEPOSIT_AMOUNT = 1e9;
