export {
  VALIDATOR_NUMBER,
  AGGREGATE_THRESHOLD,
  TOTAL_GENERATORS,
  LIST_LENGTH,
  MINIMUM_DEPOSIT_AMOUNT,
  WITHDRAW_DOWN_PAYMENT,
  BATCH_SIZE,
  MAX_SETTLEMENT_PER_BATCH,
  MAX_DEPOSIT_PER_BATCH,
  MAX_WITHDRAWAL_PER_BATCH,
  ACTION_QUEUE_SIZE,
};

const VALIDATOR_NUMBER = 60;
const AGGREGATE_THRESHOLD = 32;
const LIST_LENGTH = AGGREGATE_THRESHOLD;
const TOTAL_GENERATORS = LIST_LENGTH - 1;
const MINIMUM_DEPOSIT_AMOUNT = 1e9;
const WITHDRAW_DOWN_PAYMENT = 1e9;
const BATCH_SIZE = 80;
const MAX_SETTLEMENT_PER_BATCH = 1;
const MAX_DEPOSIT_PER_BATCH = BATCH_SIZE;
const MAX_WITHDRAWAL_PER_BATCH = 9;
const ACTION_QUEUE_SIZE = 4000;
