import * as grpc from "@grpc/grpc-js";

import type {
    GetBlockByHeightResponse,
    GetLatestBlockResponse,
    GetLatestValidatorSetResponse,
    GetValidatorSetByHeightResponse,
} from "./generated/cosmos/base/tendermint/v1beta1/query.js";
import type { QueryVoteExtBodyByHeightResponse } from "./generated/pulsarchain/abci/query.js";
import type { QueryVoteExtensionsResponse } from "./generated/pulsarchain/votepersistence/v1/query.js";
import type { QueryGetValidatorSetWithMinaKeysResponse } from "./generated/pulsarchain/keyregistry/v1/query.js";

// Typed grpc-js clients generated by ts-proto (outputServices=grpc-js) from
// the vendored protos — the generated codecs ARE the transport, nothing is
// parsed at runtime. Construct with `new XClient(address, credentials)`.
export { ServiceClient as TendermintClient } from "./generated/cosmos/base/tendermint/v1beta1/query.js";
export { QueryClient as AbciQueryClient } from "./generated/pulsarchain/abci/query.js";
export { QueryClient as KeyregistryClient } from "./generated/pulsarchain/keyregistry/v1/query.js";
export { QueryClient as VotePersistenceClient } from "./generated/pulsarchain/votepersistence/v1/query.js";

export type {
    GetBlockByHeightResponse,
    GetLatestBlockResponse,
    GetLatestValidatorSetResponse,
    GetValidatorSetByHeightResponse,
    QueryVoteExtBodyByHeightResponse,
    QueryVoteExtensionsResponse,
    QueryGetValidatorSetWithMinaKeysResponse,
};

// Raw value of a proto `bytes` field. gRPC delivers Buffers (a Uint8Array
// subclass), but JSON-transcoded responses may carry base64 strings; normalize
// with protoBytesToBuffer.
export type ProtoBytes = Buffer | Uint8Array | string;

export type GrpcCallback<TRes> = (
    err: grpc.ServiceError | null,
    res: TRes,
) => void;

// Promisify a single callback-style gRPC call:
//   const res = await grpcUnary((cb) => client.method(req, cb));
export function grpcUnary<TRes>(
    call: (cb: GrpcCallback<TRes>) => void,
): Promise<TRes> {
    return new Promise<TRes>((resolve, reject) => {
        call((err, res) => (err ? reject(err) : resolve(res)));
    });
}

export function isServiceError(err: unknown): err is grpc.ServiceError {
    return err instanceof Error && "code" in err;
}

// Normalize a proto `bytes` field: gRPC delivers Buffers, JSON-transcoded
// responses deliver base64 strings.
export function protoBytesToBuffer(val: ProtoBytes | null | undefined): Buffer {
    if (val == null) return Buffer.alloc(0);
    if (Buffer.isBuffer(val)) return val;
    if (typeof val === "string") return Buffer.from(val, "base64");
    return Buffer.from(val);
}

export function protoBufferToDecStr(
    val: ProtoBytes | null | undefined,
): string {
    const buf = protoBytesToBuffer(val);
    if (buf.length === 0) return "0";
    return BigInt("0x" + buf.toString("hex")).toString();
}
