// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cosmos/minakeys/query.proto

package minakeys

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName      = "/cosmos.minakeys.Query/Params"
	Query_KeyStore_FullMethodName    = "/cosmos.minakeys.Query/KeyStore"
	Query_KeyStoreAll_FullMethodName = "/cosmos.minakeys.Query/KeyStoreAll"
	Query_VoteExt_FullMethodName     = "/cosmos.minakeys.Query/VoteExt"
	Query_VoteExtAll_FullMethodName  = "/cosmos.minakeys.Query/VoteExtAll"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of KeyStore items.
	KeyStore(ctx context.Context, in *QueryGetKeyStoreRequest, opts ...grpc.CallOption) (*QueryGetKeyStoreResponse, error)
	KeyStoreAll(ctx context.Context, in *QueryAllKeyStoreRequest, opts ...grpc.CallOption) (*QueryAllKeyStoreResponse, error)
	// Queries a list of VoteExt items.
	VoteExt(ctx context.Context, in *QueryGetVoteExtRequest, opts ...grpc.CallOption) (*QueryGetVoteExtResponse, error)
	VoteExtAll(ctx context.Context, in *QueryAllVoteExtRequest, opts ...grpc.CallOption) (*QueryAllVoteExtResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) KeyStore(ctx context.Context, in *QueryGetKeyStoreRequest, opts ...grpc.CallOption) (*QueryGetKeyStoreResponse, error) {
	out := new(QueryGetKeyStoreResponse)
	err := c.cc.Invoke(ctx, Query_KeyStore_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) KeyStoreAll(ctx context.Context, in *QueryAllKeyStoreRequest, opts ...grpc.CallOption) (*QueryAllKeyStoreResponse, error) {
	out := new(QueryAllKeyStoreResponse)
	err := c.cc.Invoke(ctx, Query_KeyStoreAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VoteExt(ctx context.Context, in *QueryGetVoteExtRequest, opts ...grpc.CallOption) (*QueryGetVoteExtResponse, error) {
	out := new(QueryGetVoteExtResponse)
	err := c.cc.Invoke(ctx, Query_VoteExt_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VoteExtAll(ctx context.Context, in *QueryAllVoteExtRequest, opts ...grpc.CallOption) (*QueryAllVoteExtResponse, error) {
	out := new(QueryAllVoteExtResponse)
	err := c.cc.Invoke(ctx, Query_VoteExtAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of KeyStore items.
	KeyStore(context.Context, *QueryGetKeyStoreRequest) (*QueryGetKeyStoreResponse, error)
	KeyStoreAll(context.Context, *QueryAllKeyStoreRequest) (*QueryAllKeyStoreResponse, error)
	// Queries a list of VoteExt items.
	VoteExt(context.Context, *QueryGetVoteExtRequest) (*QueryGetVoteExtResponse, error)
	VoteExtAll(context.Context, *QueryAllVoteExtRequest) (*QueryAllVoteExtResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) KeyStore(context.Context, *QueryGetKeyStoreRequest) (*QueryGetKeyStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeyStore not implemented")
}
func (UnimplementedQueryServer) KeyStoreAll(context.Context, *QueryAllKeyStoreRequest) (*QueryAllKeyStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeyStoreAll not implemented")
}
func (UnimplementedQueryServer) VoteExt(context.Context, *QueryGetVoteExtRequest) (*QueryGetVoteExtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteExt not implemented")
}
func (UnimplementedQueryServer) VoteExtAll(context.Context, *QueryAllVoteExtRequest) (*QueryAllVoteExtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteExtAll not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_KeyStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetKeyStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).KeyStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_KeyStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).KeyStore(ctx, req.(*QueryGetKeyStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_KeyStoreAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllKeyStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).KeyStoreAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_KeyStoreAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).KeyStoreAll(ctx, req.(*QueryAllKeyStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VoteExt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetVoteExtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VoteExt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_VoteExt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VoteExt(ctx, req.(*QueryGetVoteExtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VoteExtAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllVoteExtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VoteExtAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_VoteExtAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VoteExtAll(ctx, req.(*QueryAllVoteExtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.minakeys.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "KeyStore",
			Handler:    _Query_KeyStore_Handler,
		},
		{
			MethodName: "KeyStoreAll",
			Handler:    _Query_KeyStoreAll_Handler,
		},
		{
			MethodName: "VoteExt",
			Handler:    _Query_VoteExt_Handler,
		},
		{
			MethodName: "VoteExtAll",
			Handler:    _Query_VoteExtAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/minakeys/query.proto",
}
