version: 1
validation: consumer
accounts: 
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
  app:
    
    grpc:
      address: localhost:9091

- name: validator1
  bonded: 100000000stake
  app:
    
    grpc:
      address: localhost:9091

- name: validator2
  bonded: 200000000stake
  app:
   
    grpc:
      address: localhost:9091

- name: validator3
  bonded: 300000000stake
  app:
    grpc.address: localhost:9091
    grpc:
      address: localhost:9091

genesis:
  consensus:
    params:
      abci:
        vote_extensions_enable_height: "1"


  

