version: 1
validation: consumer
accounts: 
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
  app:
    grpc:
      address: localhost:9091
  config:
    consensus:
      timeout_propose: "5s"
      timeout_propose_delta: "1s"
      timeout_prevote: "3s"
      timeout_prevote_delta: "500ms"
      timeout_precommit: "3s"
      timeout_precommit_delta: "500ms"
      timeout_commit: "10s"
- name: validator1
  bonded: 100000000stake
  app:
    grpc:
      address: localhost:9091
  config:
    consensus:
      timeout_propose: "5s"
      timeout_propose_delta: "1s"
      timeout_prevote: "3s"
      timeout_prevote_delta: "500ms"
      timeout_precommit: "3s"
      timeout_precommit_delta: "500ms"
      timeout_commit: "10s"

- name: validator2
  bonded: 200000000stake
  app:
    grpc:
      address: localhost:9091
  config:
    consensus:
      timeout_propose: "5s"
      timeout_propose_delta: "1s"
      timeout_prevote: "3s"
      timeout_prevote_delta: "500ms"
      timeout_precommit: "3s"
      timeout_precommit_delta: "500ms"
      timeout_commit: "10s"

- name: validator3
  bonded: 300000000stake
  app:
    grpc:
      address: localhost:9091
  config:
    consensus:
      timeout_propose: "5s"
      timeout_propose_delta: "1s"
      timeout_prevote: "3s"
      timeout_prevote_delta: "500ms"
      timeout_precommit: "3s"
      timeout_precommit_delta: "500ms"
      timeout_commit: "10s"

genesis:
  consensus:
    params:
      abci:
        vote_extensions_enable_height: "1"
      block:
        time_iota_ms: "10000"


  

